### ISSUE TITLE
Suggestion: Hopper pots

### ISSUE THREAD

**Issue by trollsdottir** [Darkhax-Minecraft/BotanyPots#10]
I noticed that when the inventory connected to the hopper pot is full, the pot is still simulating the growth (visually) even though there is no output due to lack of inventory space.. Could they be set to stop the growth cycle (to indicate the full inventory)?

I thought that it also be neat to make the hopper pot redstone dependent, so that one could use lever to stop it from making excessive resources.

**Comment by Darkhax** [comment]
Thanks for the suggestion. It sounds like the first part is a bug. I will look into fixing that. As for the redstone signal, that is a good idea and I will look into it.

**Comment by Darkhax** [comment]
Fixed the visual growing bug in https://github.com/Darkhax-Minecraft/BotanyPots/commit/9dba80b504bb4e5c8635197df5be7d6c4e0ff049 and added redstone control in https://github.com/Darkhax-Minecraft/BotanyPots/commit/b40ade0a45424b0d367c50e1c6255aaca94e007d.

You can find the release [here](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/2884820)
