### ISSUE TITLE
Datapack help 1.15

### ISSUE THREAD

**Issue by InfinitysDaughter** [Darkhax-Minecraft/BotanyPots#101]
I'm trying to add a datapack for the Ore Reeds mod. I've copy and pasted the data from default files then just replaced the item IDs. I got the IDs using the tellme mod so they are accurate IDs. The datapack loads but the recipe wont and I'm not sure what I'm doing wrong. Any help would be wonderful.

[botpotcustom-20201103T192233Z-001.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5483622/botpotcustom-20201103T192233Z-001.zip)

**Comment by Darkhax** [comment]
Hello, I think the issue is that you have a space in the ore reeds folder name. The game generates your recipe IDs using folder/file names and IDs can not have spaces in them.

**Comment by InfinitysDaughter** [comment]
Thats what I thought but it didn't work that way either. I've tried with a space, no space, and an underscore (_) and none of it worked. @w@

**Comment by Darkhax** [comment]
Finally worked this out. You had many small issues and typos in your files which caused it to break at many different spots. Here are the changes I made to get this working.

- pack_format in pack.mcmeta should be 4 on 1.15.2
- You typoed recipes as recipies in the folder structure.
- folders can not have spaces like "ore reeds"
- Recipe type for crops was mispelled with an s at the end.
- Soil was missing a `growthModifier` property.

[custompots-fixed.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5571939/custompots-fixed.zip)
