### ISSUE TITLE
Call me a Noob but I can't seem to integrate Xy.. I mean ZyCraft's Zychorium Soil with Craft Tweaker

### ISSUE THREAD

**Issue by Algester** [Darkhax-Minecraft/BotanyPots#105]
import mods.botanypots.ZenSoil;
val soils = <recipetype:botanypots:soil>;

// soils.create(id, input, renderBlock, growthModifier, category);
// Growth can be any value less than or equal to 1. Higher = faster, 0 = no change.
// category may also be a string array.
val zyCraftSoil = soils.create("ZyCraftFarm:ZychoriumSoil", <zycraft:zychorium_soil>, <blockstate:zycraft:zychorium_soil>, 0.45, "Zychorium Soil");

this is currently what I have in Zen Scripts although without looking deep into forgecraft playthroughs I don't think anyone actually made Zycraft soil in botany pots did they?

**Comment by Darkhax** [comment]
Are you getting any errors in your console? I see a lot of issues here. For example no angle brackets around the recipe type, item, blockstate, and a bunch of upper case characters in your IDs which are not allowed.

Imagine a block called Test Dirt from a mod called Example Mod. You do f3+h to get advanced tooltip info and the tooltip says it's called `example:test_dirt`. When looking at the block with the f3 screen up it also says 'example:test_dirt' for the block state, this is visible on the right side of the info overlay.

Your script file would look like this.

```zenscript
import mods.botanypots.ZenSoil;
val soils = <recipetype:botanypots:soil>;

val testDirt = soils.create("your_modpack:example_dirt", <example:test_dirt>, <blockstate:example:test_dirt>, 0.15, "dirt");
```

**Comment by Algester** [comment]
yep I'm getting errors all right
```
import mods.botanypots.ZenSoil;
val soils = <recipetype:botanypots:soil>;

// soils.create(id, input, renderBlock, growthModifier, category);
// Growth can be any value less than or equal to 1. Higher = faster, 0 = no change.
// category may also be a string array.
val zyCraftSoil = soils.create("zycraft:zychorium_soil", <zycraft:zychorium_soil>, <blockstate:zycraft:zychorium_soil>, 0.45, "Zychorium Soil");

```
this is how the code looks

**Comment by Algester** [comment]
it maybe fixed down the line
import mods.botanypots.ZenSoil;
val soils = <recipetype:botanypots:soil>;
val zyCraftSoil = soils.create("item_zycraft_zychorium_soil", <item:zycraft:zychorium_soil>, <blockstate:zycraft:zychorium_soil>, 0.5, "dirt");
but here's the right script welp that was a doozy of syntaxes
