### ISSUE TITLE
Ability to Select blockstate Age when creating a new crop using CraftTweaker

### ISSUE THREAD

**Issue by Drakma** [Darkhax-Minecraft/BotanyPots#106]
There is currently no way (that I can see) to use CraftTweaker and use an age other than 1 for Blockstate.

This would be a nice enhancement as flower from MysticalAgriculture all use the same age 1 image.

**Comment by Darkhax** [comment]
The CraftTweaker documentation explains how to define block state properties. https://docs.blamejared.com/1.16/en/vanilla/api/blocks/MCBlockState/

The specific part is the `withProperty` method. For example `<blockstate:minecraft:grass_block>.withProperty("snowy", true)
