### ISSUE TITLE
1.15.2 Botany pots don't save their dirt/seed contents on full game reload

### ISSUE THREAD

**Issue by elowanut** [Darkhax-Minecraft/BotanyPots#11]
This is on the latest version of Botany Pots ( BotanyPots-1.15.2-2.0.1), Bookshelf ( Bookshelf-1.15.2-5.1.3) and with Forge 31.1.18.

As stated in the title, both regular and hopper pots do not save their contents once you have quit and re-entered Minecraft. 

Replicate as follows: 

Start a fresh world, place down a couple of regular pots and/or hopper pots. Fill them with dirt, and place a seed on them. I've tried both regular seeds (like wheat), and custom seeds (I had added Inferium seeds from Mystical Agriculture as a datapack). The plants will grow and replant as normal (either manually harvesting the regulars, or into a storage system for the hopper pots). 

Then quit the game, and close out Minecraft. Note that you can't just quit to the title menu, and re-enter the save game. Pot states seem to be preserved if you do that. As soon as you close out the whole game and restart / re-enter the world, your pots will be in place, but empty of both seeds and dirt. 

This seems to happen in both survival and creative. Also, to be clear, I first noticed this while running 40+ mods, but I tested with just Forge/Botany/Bookshelf.

**Comment by Darkhax** [comment]
Thanks for reporting this. This is actually an issue in the Bookshelf mod which has been fixed in version 5.0.4.
