### ISSUE TITLE
Harvestcraft Compatibility Issue

### ISSUE THREAD

**Issue by Entorien** [Darkhax-Minecraft/BotanyPots#113]
Using BotanyPots-1.16.4-6.0.5 as part of the All The Mods 6 pack, and I can't get Harvestcraft crops to go in the pots. I've tried with several different pots and crops, the dirt goes in just fine and I'm using them for Botania flowers, but Harvestcraft crops just refuse.

I tried looking for the data/modid/recipes folder to see if something was awry, but that folder wasn't there.

I'm a bit lost, tbh.

**Comment by Darkhax** [comment]
I've downloaded All The Mods 6 and it's working just fine. This is version 1.3.3 of their pack. Perhaps this is just for certain crops? 
![image](https://user-images.githubusercontent.com/2250798/101485448-1443f980-3953-11eb-97c7-86de5cb6b4ba.png)
