### ISSUE TITLE
Request - Support for Farming for Blockheads

### ISSUE THREAD

**Issue by BriceFable** [Darkhax-Minecraft/BotanyPots#118]
Farming for Blockheads adds multiple fertilizers and soils (speed growth, crop output, no trampling). I was wondering if it would be possible to make them compatible with the botany pots.

https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads

**Comment by ModernGamingWorld** [comment]
https://github.com/Darkhax-Minecraft/BotanyPots/pull/122

Somewhat added here

**Comment by Darkhax** [comment]
I think this should work now. If any soils/plants/fertilizers don't work please let me know the specific ones and I will add them to my TODO list.

**Comment by thisisyoursus** [comment]
still Todo?
