### ISSUE TITLE
Simple farming turnip seed

### ISSUE THREAD

**Issue by Pixle36** [Darkhax-Minecraft/BotanyPots#13]
When I put a turnip seed in a hopper botany pot with dirt as the soil, it instagrows repeatedly with no grow time yielding drops into the barrel below every time 
[Video of it happening](https://drive.google.com/file/d/1XJCoYv3jDhLgIhjSNdAZ5C8v6dC4CFpX/view?usp=drivesdk)

**Comment by Darkhax** [comment]
Thanks for reporting, this should now be fixed.
