### ISSUE TITLE
Java No Class Def Found Error

### ISSUE THREAD

**Issue by judicius** [Darkhax-Minecraft/BotanyPots#130]
BotanyPots 6.0.14
Forge 35.1.36
MC 1.16.4

Updated to 6.0.14, server crashes on startup. Custom CraftTweaker scripts disabled, same issue.

https://gist.github.com/judicius/3535c1ba0c90e431d434553c932cc6eb

**Comment by Darkhax** [comment]
CraftTweaker had a major update with breaking changes. You need to update CraftTweaker to 7.1.x.x or higher.
