### ISSUE TITLE
crash at the start 

### ISSUE THREAD

**Issue by DamienBrittan** [Darkhax-Minecraft/BotanyPots#131]
botanypots version - BotanyPots-1.16.4-6.0.16
forge - 1.16.4-forge-35.1.36
https://gist.github.com/DamienBrittan/5600f7fa0abef72e58db48e2d8fdbd89

**Comment by Darkhax** [comment]
Thanks for reporting this issue. This should now be fixed in 6.0.17.

**Comment by DamienBrittan** [comment]
it's not supported with 1.16.4 version

**Comment by DamienBrittan** [comment]
same as bookshelf
