### ISSUE TITLE
[REQUEST 1.16.x] compatibility for mystical agradditions' crux

### ISSUE THREAD

**Issue by mthnry** [Darkhax-Minecraft/BotanyPots#133]
I found that the cruxes added by mystical agradditions for tier 6 seeds don't work in the botany pots. Would be nice if this could be added as an increased growth accelerator than supremium farmland or even a requirement for tier 6 seeds to be planted at all.

**Comment by Darkhax** [comment]
Thanks for requesting this. The crux is not a soil so it does not make sense that it would go inside the pot. Botany Pots with Mystical Agriculture is already very over powered and this idea does not fit within the scope of what this mod is or does.
