### ISSUE TITLE
Request 1.16x insanium farmland

### ISSUE THREAD

**Issue by castilio20** [Darkhax-Minecraft/BotanyPots#139]
Coul you add support for insanium farm land plss
this farmland is from mysticalagradditions
not sure if this is right 
![Screenshot_12](https://user-images.githubusercontent.com/76228548/106771932-5eb0c200-65f4-11eb-8b81-e7b19e051743.png)

**Comment by Darkhax** [comment]
This should be added in https://github.com/Darkhax-Minecraft/BotanyPots/commit/19f743dd99fa5e0855d248ea22647a35dc88d6aa
