### ISSUE TITLE
Botany Pots 1.15.2-2.0.4 Don't Accept Soil after Breaking & Replacing

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Darkhax-Minecraft/BotanyPots#14]
I'm building a pack in 1.15 and am using your mod, Botany Pots 1.15.2-2.0.4. The pots work great until I break a pot, then any pots I place afterward will not accept soil. In order to place soil in a pot, I have to restart my client otherwise the soil places like a normal block on top of the pot as if I was shift-clicking to place the block.

![botany_pot_1](https://user-images.githubusercontent.com/17887664/77218975-d10cd680-6af6-11ea-9b00-19a411abcc8f.png)

**Comment by Darkhax** [comment]
I am not able to reproduce this issue in single player or on a dedicated server. Can you share more information about your situation? Do you have any custom scripts, addons, or data packs?

**Comment by ClaudiusMinimus** [comment]
Thank you for your response.
Here is a list of mods I'm using:
https://pastebin.com/Wv5shXA0
Also, I'll test this without any other mods loading and will let you know.

**Comment by ClaudiusMinimus** [comment]
Well, this is embarrassing. All is well. I can place dirt. Whatever conflict that was there is now mysteriously gone. Thanks for your help!

**Comment by purpleposeidon** [comment]
Yeah, I can't place mycellium or grass. Dedicated server. I was able to place it client-side. After restarting the client, I was no longer able to place even client-side.
