### ISSUE TITLE
Unable to plant Mystical Flower seed from mystical agriculture 

### ISSUE THREAD

**Issue by AliyahPhelps** [Darkhax-Minecraft/BotanyPots#143]
Hello there,
I am attempting to plant a Mystical Flower seed from mystical agriculture into a pot with infernium soil. In JEI it tells me I should be able to farm this seed using the pots, yet there is nothing happening when I attempt to plant said seed. Am I doing something wrong, or is something else happening here?
![mysticalflowerseed](https://user-images.githubusercontent.com/35856544/107300643-ec067300-6a47-11eb-90cb-5b815570c666.PNG)

**Comment by Darkhax** [comment]
Mystical Flowers are a tier 2 seed, this means you need to use prudentium farmland or higher.
