### ISSUE TITLE
Hopper botany pot does not waiting for inserting items after inserting the first item

### ISSUE THREAD

**Issue by Snownee** [Darkhax-Minecraft/BotanyPots#146]
https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.16.5/src/main/java/net/darkhax/botanypots/block/tileentity/TileEntityBotanyPot.java#L309
I don't know if it is intentional but when I try to place a botany pot upon a belt in Create mod, it only outputs the first result

**Comment by Darkhax** [comment]
This is an unintended interaction but the mod is working as expected. The pot has no inventory/buffer space, it is more so like a hopper that pushes out it's contents to the bellow inventory block. If the below inventory block is full it will just void any remaining items.
