### ISSUE TITLE
[1.16.5] Hopper botany pots cannot be locked by a redstone signal

### ISSUE THREAD

**Issue by ChloeDawn** [Darkhax-Minecraft/BotanyPots#148]
**Mod version:** 1.16.5-7.0.8

Applying a redstone to a botany hopper pot does not prevent the plant from growing.

**Comment by Darkhax** [comment]
Hello, 

I removed this feature in recent MC versions because I didn't think it made sense to include. There was also a (minor) performance impact to keeping the feature. I didn't think anyone was benefiting from this feature, but if you have a reasonable use case I can look into re-adding it.
