### ISSUE TITLE
[REQUEST] mystical aggreculture powah seeds

### ISSUE THREAD

**Issue by sebtech33** [Darkhax-Minecraft/BotanyPots#152]
hi some recipes from mystical aggreculture regarding powah seeds that require insanium farmland does not work in the botany pot. or at least in TNP Limitless 3 modpack. the garden cloche has support for this so i woundered if this to could support this. talked to the modpack dev and he didn't change this. more that the botanypot didnt support it. Thanks for a great mod non the less :)

**Comment by Darkhax** [comment]
Hello, yes these can be supported. Do you have a full list of seeds so I can look into them?

**Comment by Superlamaface** [comment]
Here is a list of the seeds I could find. Mind you this is in 1.16.5.
In-game picture with fully grown picture and essence required to make them: https://imgur.com/a/xMy8gzl

**Mods:**
MysticalAgradditions-1.16.4-4.1.5
MysticalAgriculture-1.16.4-4.2.0
Powah-1.16.5-2.3.16
BotanyPots-1.16.5-7.1.23

**List:**
Energized Steel (Tier: 4)
Blazing Crystal (Tier: 4)
Niotic Crystal (Tier: 5)
Spirited Crystal (Tier: 5)
Nitro Crystal (Tier: 6)

**Edit:** The only seed missing currently is the Nitro Crystal Seed.

**Comment by CarlosLab3** [comment]
insert nitro crystal seed via datapack,
[nitro_crystal.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/6932185/nitro_crystal.zip)

**Comment by amouranthtoo** [comment]
This is patched in the latest update
