### ISSUE TITLE
Harvestcraft 2 issues

### ISSUE THREAD

**Issue by XavierDare** [Darkhax-Minecraft/BotanyPots#153]
Hi, I am trying to use Harvestcraft 2 with it and i cant get any crops inside of the pot or the trees. I have tried with both dirt and grass as the soil.

**Comment by XavierDare** [comment]
![image](https://user-images.githubusercontent.com/64657541/110021834-3b635a80-7cf9-11eb-9d07-ba414ded8b3a.png)

**Comment by AlleCraft-alterego** [comment]
https://www.curseforge.com/minecraft/mc-mods/botany-trees
don't have support harvestercraft 2
you need see on jei if crop/trees is supported

**Comment by Darkhax** [comment]
Yes, this mod does not support Trees by default. [Botany Trees](https://www.curseforge.com/minecraft/mc-mods/botany-trees) has Pam's Trees support, even if it's not listed on the mod page. I support like 30 mods now so the list would get too big lol.

If any of the non-tree plants don't plant let me know so I can fix them.
