### ISSUE TITLE
[1.16.5] Lost Crops on update

### ISSUE THREAD

**Issue by NielsPilgaard** [Darkhax-Minecraft/BotanyPots#157]
When updating from `BotanyPots-1.16.5-7.0.8` to `BotanyPots-1.16.5-7.0.9`, all Botany Pots lost their crops. 

Using `Forge-1.16.5-36.1.0`

Relayed from https://github.com/NillerMedDild/Enigmatica6/issues/1789

**Comment by Darkhax** [comment]
There were no significant changes from 7.0.8 to 7.0.9. Can you reproduce the issue and provide logs from when the world loads?

**Comment by NielsPilgaard** [comment]
Hmm, maybe it was caused by the Forge update from `36.0.44` to `36.1.0` then :/

> Can you reproduce the issue and provide logs from when the world loads?

I'll try :)

**Comment by NielsPilgaard** [comment]
Neither Forge update nor Botany Pots update did anything to existing Pots, sorry about that :)
