### ISSUE TITLE
Soil disappearing from pots

### ISSUE THREAD

**Issue by Chunkimunki** [Darkhax-Minecraft/BotanyPots#16]
2.0.5 version   -   forge-31.1.30

On restarting game and joining world soil / crop has gone from both type of pots.
If it helps here's the log  [pastebin](https://pastebin.com/WLruPTzg)

Like your work lots BTW

**Comment by Darkhax** [comment]
Hello, 

The game log you uploaded is saying that the game is not even starting because Bookshelf needs a newer version of Forge. Is this the latest log file?

**Comment by Chunkimunki** [comment]
Hi there my friend, apologies for the goof. Thought I'd given the correct log. As an old fart this is a bit new trying to help out with all you fab modders.
Hope this will be a smidge more illuminating [pastebin](https://pastebin.com/vhE6xKVz)

Joined new world - placed 1 pot / 1 hopper pot - added dirt and wheat seed then quit.

Cheers

**Comment by Darkhax** [comment]
Thanks for trying to upload the log again. I think I may have just missed the expiration on it. Pastebin says 
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

**edit:** Looks like you had an extra character on the URL. Got it working now though, thanks.

**Comment by Chunkimunki** [comment]
Dang these fat fingers! lol

**Comment by Darkhax** [comment]
A [new version](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/2916186) is now on the Curse page. Could you please test it out and let me know if it works?

**Comment by Chunkimunki** [comment]
By Jingo - you've only gone and cracked it! Works perfectly - your a star!

**Comment by Darkhax** [comment]
That's great, thank you for reporting this issue and helping test the fix.
