### ISSUE TITLE
[Compatibility] Pollution of the Realms?

### ISSUE THREAD

**Issue by EliotWL** [Darkhax-Minecraft/BotanyPots#161]
Could we get compatibility for PotR? [I asked them about it ](https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms/issues/125) but they said it could only be done on your end.  Maybe you might need to work together if it can't be just one sided?

**Comment by Darkhax** [comment]
No idea what this mod does or what compatibility would look like. I also can't find the src for their mod so I have no idea how they're using IGrowable.

**Comment by EliotWL** [comment]
The mod adds pollution that is given off from burning things and other sources.  One of the blocks is a carbon gas pollution which when it touches plants it helps them grow faster (but animals/the player get suffocated), this doesn't seem to work on things in the botany pots (hence my asking about it).

Like I said, you likely would have to work with them on the solution because they aren't open source and punted me to you when I asked them.

**Comment by EnderLanky** [comment]
Since we are all gathered here, I'll try to explain. What we need is that every call of the **BlockBotanyPot.grow** method leads to a noticeable plant growth by adding either a configurable or the same number of **ticksToGrow** as bone meal does. Of course, unless it conflicts with your mod design.

**Comment by Darkhax** [comment]
> 
> 
> Since we are all gathered here, I'll try to explain. What we need is that every call of the **BlockBotanyPot.grow** method leads to a noticeable plant growth by adding either a configurable or the same number of **ticksToGrow** as bone meal does. Of course, unless it conflicts with your mod design.

So from what I gather, the mod does actually work with Botany Pots, but I only add one tick so the effect is practically non-existent? Should be easy to make it add a more noticeable amount of ticks here if that's the case.

**Comment by EnderLanky** [comment]
That's right, it works fine, we just need more ticks to see the actual growth.

**Comment by Darkhax** [comment]
This should be fixed in 7.1.X builds. The growth should add 3-15 seconds worth of growth.
