### ISSUE TITLE
[1.16.5] Mystical Agriculture crop names aren't localized

### ISSUE THREAD

**Issue by ocram9** [Darkhax-Minecraft/BotanyPots#163]
See https://github.com/BlakeBr0/MysticalAgriculture/issues/424 for more info.

**Comment by Darkhax** [comment]
The current change was made to accommodate The One Probe which generates the displayed info on the server. Blake's suggested solution requires code that only exists on the client so it can not be used with The One Probe. 

I will look into fixing this for Hwyla, but TOP support will likely remain broken.

**Comment by Darkhax** [comment]
After further review this issue is actually on Mystical Agriculture's end and they've already fixed it.
