### ISSUE TITLE
Suggestion: JEI list of soils with modifiers

### ISSUE THREAD

**Issue by LabGoblin** [Darkhax-Minecraft/BotanyPots#164]
It would be nice to see a list of soils and their modifiers.

Something similar to the Crucible Heat Sources from Ex Nihilo: Sequentia (shown below) would be awesome.

![image](https://user-images.githubusercontent.com/10270884/120239623-478d8400-c224-11eb-805c-425dbf8641ec.png)

Thanks in advance.

**Comment by Darkhax** [comment]
This feature should be implemented now. Thanks for the suggestion.
