### ISSUE TITLE
Atum 2 Compat

### ISSUE THREAD

**Issue by Late-Night** [Darkhax-Minecraft/BotanyPots#167]
allow flax, emmer, and anput's fingers spores to be grown in botany pots
soil would be Fertile Soil for the former two, and Strange Sand for the latter

**Comment by ngoetti** [comment]
I can not get anput's fingers spores to grow on Strange Sand

**Comment by ngoetti** [comment]
Anput's fingers spores is currently not supported because I can't get them to grow on Strange Sand. The rest works as intended.
