### ISSUE TITLE
Fluorite Seeds not Supported (Mystical Agriculture)

### ISSUE THREAD

**Issue by lemonlambda** [Darkhax-Minecraft/BotanyPots#168]
You can't plant Fluorite Seeds inside of a botany pot of any soil

Tested with Hopper Botany Pot with Supremium Farmland
![image](https://user-images.githubusercontent.com/55360995/121742512-eab88600-cacd-11eb-94fd-cb977c350459.png)
This image also shows there is no recipes for the fluorite seed

**Comment by lemonlambda** [comment]
I created a pr for this issue

**Comment by Darkhax** [comment]
Thanks for helping to fix this issue.
