### ISSUE TITLE
[1.15.2] Mystical Agriculture crop ID instead of crop name with hwyla

### ISSUE THREAD

**Issue by ocram9** [Darkhax-Minecraft/BotanyPots#17]
When looking at a Mystical Agriculture crop in a pot with hwyla, the ID of the crop is visible instead of the name of the crop: 

![Crop name](https://user-images.githubusercontent.com/49008532/78312793-38923f80-7555-11ea-8128-7da1edfc6a65.jpeg)

**Versions**
- Minecraft 1.15.2
- BotanyPots-1.15.2-2.0.6
- Bookshelf-1.15.2-5.3.10
- Forge 31.1.35

**Comment by Darkhax** [comment]
My mod just shows the block name, this is their issue.
