### ISSUE TITLE
Tinker's Construct's Mystical Agriculture seeds need a compat fix

### ISSUE THREAD

**Issue by justwlocke** [Darkhax-Minecraft/BotanyPots#172]
All seeds from Mystical Agriculture for Tinkers Construct, are unable to be grown in Botany Pots.
This includes...
Tinker's Bronze
Slimesteel
Pig Iron
Cobalt
Rose Gold
Manyullyn
Queens Slime
Hepatizon

**Various Versions**
Minecraft: 1.16.5
Forge: 36.1.24
Cucumber: 1.16.4-4.1.9
Botany Pots: 1.16.4-7.0.18
Mystical Agriculture: 1.16.4-4.1.18
Tinker's Construct: 1.16.5-3.0.4.171

**Comment by Diversion98** [comment]
Do u have crafttweaker in the pack?
U can always add new crops with crafttweaker :)

**Comment by fatpally** [comment]
Been trying to do such this but it asks for a zencrop value for the seeds when trying to do the output

**Comment by Diversion98** [comment]
The following is an example for earthslime:

import mods.botanypots.ZenCrop;

val crops = <recipetype:botanypots:crop>;

val earthSlimeCrop = crops.create("tconstruct:earthslime", <item:tconstruct:earth_slime_sapling>, <blockstate:tconstruct:earth_slime_sapling:stage=0>, 1200, "slime");

**Comment by ModernGamingWorld** [comment]
Fixed here https://github.com/Darkhax-Minecraft/BotanyPots/commit/91601561cd82f0dc480c6d57ce606b238f09d7b0

**Comment by Darkhax** [comment]
Thanks for the report, this should now be resolved thanks to the help of ModernGamingWorld. If there are any issues with the latest update let me know.
