### ISSUE TITLE
Hopper Pots with melons do not produce any fruit.

### ISSUE THREAD

**Issue by SargeRyong** [Darkhax-Minecraft/BotanyPots#175]
Couldnt get hopper pots to produce melons no matter how hard I tried.  Normal botany pots did produce melons normally when right clicking them when fully grown.

Steps to reproduce:

1. Place a vanilla chest.
2. Place a Hopper Botany Pot on top of that chest.
3. Right click soil into the pot.
4. Right click melon seeds into the pot.
5. Spam right-click bone meal on the pot until there are only a handful of seconds until growth completes.
6. Wait the last few seconds for the melon to finish growing.
7. Observe that the melon "pops" and the breaking noise plays as the pot returns to the first growth stage.
8. Open the chest and observe that there are no melons in the chest.

**Comment by SargeRyong** [comment]
Update: It appears that it only fails to produce fruit the FIRST time the plant grows to maturity.  If you let it continue to grow afterwards it will begin producing fruit starting on the second cycle.

Standard botany pots appear to always produce fruit on the first cycle.

**Comment by Darkhax** [comment]
The drops of crops are luck based. It is possible to get no drops. The melon specifically is a 75% chance to give 1 melon and a 5% chance to drop 1-2 seeds.

**Comment by SargeRyong** [comment]
For what it's worth, I don't believe this was just chance.   I was able to repeat it 14 times in a row that the first growth iteration didn't produce fruit.  Not as big of a deal since it's apparent that only the first growth has an issue, but still strange.

**Comment by Darkhax** [comment]
Okay, I will look into this some more.
