### ISSUE TITLE
Botany Pot's not accepting crop seeds in Modpack (Seaopolis)

### ISSUE THREAD

**Issue by RMckinney100** [Darkhax-Minecraft/BotanyPots#176]
I was able to use Hopper Botany Pots to create a tree farm but won't accept any seed types even with other dirt types inside the pot.

The seeds I'm referring too are the basic Minecraft seeds as well as Ex Nihilo: Sequentia seeds except for Sugarcane and Cactus with sand placed in the pot.

I tried using normal dirt, farmland, rich soil and other types in creative and nothing seemed to work.

**Comment by Darkhax** [comment]
This modpack has intentionally removed virtually all of the seeds. The only seeds that will work are the ones shown in JEI.
