### ISSUE TITLE
CropID syntax for existing mod crops unknown

### ISSUE THREAD

**Issue by jengendler** [Darkhax-Minecraft/BotanyPots#178]
Similar to my [request to know the cropids for vanilla trees](https://github.com/Darkhax-Minecraft/BotanyPots/issues/117) (thank you!), I would like to know the syntax for existing crops from other mods (not vanilla) that are supported and pre-loaded by this mod. My goal is to modify an existing mod's crop/soil/fertilizer, but I don't know the 'cropid' to target it properly.

For example, for Environmental, cattails seeds can be planted on farmland, grow cattails, and then be right-clicked to harvest cattail seeds. However the pre-loaded crops are just cattails in > cattails out and tall_cattails in > tall_cattails out. So, I've created a custom crop to allow the seed to be planted, grow cattails, and harvest seeds as the output. I would like to be able to remove the pre-existing cattail crops, but don't know how the cropid. For example, I have tried the following which do not work:

```
botanypots:environmental/cattail
botanypots:crop/cattail
environmental:crop/cattail
```

It would also be useful to know the syntax for existing modded trees (Botany Trees) if they are different.

Is there a Craft Tweaker command that will print a list of cropids by chance? I mostly wish there was an Advanced Tooltip to show cropid in JEI when I have those turned on, similar to recipeid. If I am overlooking anything, please let me know! :)

Thank you!

**Comment by Darkhax** [comment]
You can find all crops, soils, etc [here](https://github.com/Darkhax-Minecraft/BotanyPots/tree/1.16.5/src/main/resources/data), and the cattail one is [here](https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.16.5/src/main/resources/data/environmental/recipes/crops/cattail.json).

Ids are generates using the folder structure and placement of the file. For example the cattail file is `data/environmental/recipes/crops/cattail.json`. 

The data and recipe folder are ignored, so is the file extension which leaves you with `environmental/crops/cattail`. The first folder is used as the namespace (the part before the first `:`) and the rest is used as the actual id. So it becomes `environmental:crops/cattail`

**Comment by jengendler** [comment]
Super helpful. Thank you!
