### ISSUE TITLE
Mystical Agriculture, botanypots e powah

### ISSUE THREAD

**Issue by AJOTINHA** [Darkhax-Minecraft/BotanyPots#179]
Can someone help me? I can't put the nitro seed to plant in the botanypots

**Comment by CarlosLab3** [comment]
you can insert via datapack (\.minecraft\saves\yoursave\datapacks\botanypots\data\miysticalagriculture\recipes\crops)
[nitro_crystal.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/6931985/nitro_crystal.zip)

**Comment by amouranthtoo** [comment]
This Has been Fixed in the latest release tho if i was u i would use this
[nitro_crystal.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/7555782/nitro_crystal.zip)
