### ISSUE TITLE
Compatibility

### ISSUE THREAD

**Issue by obed531** [Darkhax-Minecraft/BotanyPots#18]
How can i make this mod compatible with mystcraft? or Croparia mod on MC 1.15.2, what i need to download and where i need to put it?

**Comment by Darkhax** [comment]
Mystcraft and Croparia are not officially supported at this time. If you want to add support yourself you can use the [data pack system](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Datapack-Information) to code it.

**Comment by LCWuShang** [comment]
How can i make this mod compatible with mystcraft? or Croparia mod on MC 1.16.5, what i need to download and where i need to put it?

**Comment by Darkhax** [comment]
@LCWuShang For the mod to be compatible someone would need to write datapack files. The standard process is for me or someone else to sit down and write the pack and then add it into the official mod. In this case nobody has come forward with support for MystCraft and someone on Discord has been working on Croparia.

**Comment by LCWuShang** [comment]
@Darkhax thx 😁
