### ISSUE TITLE
Compatibility for Ars nouveau 

### ISSUE THREAD

**Issue by RCelty** [Darkhax-Minecraft/BotanyPots#181]
Hi, first I want to say that I love your mod very much.
Currently I have been playing your mod together with Ars nouveau, and it would be great if I can grow mana crops and trees from Ars nouveau in Botany pot. I hope I can do it in the near future.
Love your works

**Comment by Darkhax** [comment]
Thanks for the request. The crops should already be growable. Trees are handled by a separate addon called [Botany Trees](https://www.curseforge.com/minecraft/mc-mods/botany-trees) which likely doesn't support ars nouveau trees yet but I can add it to my TODO list.
