### ISSUE TITLE
Duplicate crop recipes for Farmer's Delight

### ISSUE THREAD

**Issue by jengendler** [Darkhax-Minecraft/BotanyPots#183]
Mod Version: 7.1.23

Farmer's Delight (1.6.5-0.4.6) has built-in Botany Pot integration for its modded soils and crops. The current BotanyPots version (1.16.5-7.1.23) has Farmer's Delight soil and crop recipes that create duplicates/conflicts, namely for Rich Soil Farmland, Cabbage, and Tomatoes. Farmer's Delight contains all its soils and crops recipes for Botany Pots in its mod. I suggest removing Farmer's Delight recipes from BotanyPots to ensure better compatibility.

**Comment by Darkhax** [comment]
Thanks, this is removed in https://github.com/Darkhax-Minecraft/BotanyPots/commit/08052d9a0093f7e4ad3ed11d3769b2ff57e73417
