### ISSUE TITLE
Druidcraft, Infernal Expansion and Rewitched support

### ISSUE THREAD

**Issue by Wakatsu** [Darkhax-Minecraft/BotanyPots#184]
https://www.curseforge.com/minecraft/mc-mods/druidcraft
https://www.curseforge.com/minecraft/mc-mods/infernal-expansion
https://www.curseforge.com/minecraft/mc-mods/witchery-rewitched

These. Pretty please?

**Comment by Darkhax** [comment]
Druidcraft should already be supported. I will add the other two when I have time or if someone else wants to do it.

**Comment by Darkhax** [comment]
Infernal Expansion support has been added in 8.1.25 for 1.18.2. 

The Witchery Rewitched mod is stuck on 1.16.5 and I don't have the time to go back and work on updates for old versions. If someone wants to make a PR I will merge it though.
