### ISSUE TITLE
[Compatibility Suggestion] Industrial Agriculture

### ISSUE THREAD

**Issue by AbacusOperator** [Darkhax-Minecraft/BotanyPots#185]
Industrial Agriculture is a series of addons for Mystical Agriculture providing compatibility between Mystical Agriculture and various other mods. This series consists of [core mod](https://www.curseforge.com/minecraft/mc-mods/industrial-agriculture) which doesn't add anything by itself and the following modules dependent on it:

- [IAP [Botania]](https://www.curseforge.com/minecraft/mc-mods/iap-botania)
**Livingstone
Livingwood
Manasteel
Elementium
Terrasteel
Gaia Spirit**

- [IAP [Gobber]](curseforge.com/minecraft/mc-mods/iap-gobber)
**Glob
Nether Glob
End Glob**

- [IAP [Industrial Foregoing]](https://www.curseforge.com/minecraft/mc-mods/iap-industrial-foregoing)
**Plastic
Pink Slime**

- [IAP [Mekanism]](https://www.curseforge.com/minecraft/mc-mods/iap-mekanism)
Salt
Copper
Tin
Sulfur
Osmium
Bronze
Steel
Refined Glowstone
Refined Obsidian

- [IAP [Omega Craft]](curseforge.com/minecraft/mc-mods/iap-omega-craft)
Electrum
Copper
Lead
Silver
Tin
Aluminum
Bronze
Steel
Magmite
Cave Magmite

- [IAP [Powah]](https://www.curseforge.com/minecraft/mc-mods/iap-powah)
Uraninite

- [IAP [Silent's Gems]](https://www.curseforge.com/minecraft/mc-mods/iap-silents-gems)
Classic Gems
Dark Gems
Light Gems

- [IAP [Silent's Mechanisms]](https://www.curseforge.com/minecraft/mc-mods/industrial-agriculture-plugin-silents-mechanisms)
Lead
Enderium
Bismuth
Zinc
Redstone Alloy
Compressed Iron
Refined Iron
Platinum
Copper
Silver
Aluminum
Nickel
Brass
Bismuth Brass
Bismuth Steel
Invar
Uranium
Steel
Signalum
Aluminum Steel
Bronze
Electrum
Tin
Lumium

**Note 1**: Some of the basic metals seeds (copper, lead, etc.) from this list were for quite sometime added into original Mystical  Agriculture
**Note 2**: Mods are closed source if it possible contact their creator [ArrowsendGaming](https://www.curseforge.com/members/arrowsendgaming)
**Note 3**: I added symmetrical [request](https://www.curseforge.com/minecraft/mc-mods/industrial-agriculture/issues/18) on their issue tracker.

**Comment by Darkhax** [comment]
It looks like they've already added support on their end.
