### ISSUE TITLE
configurable grow time 

### ISSUE THREAD

**Issue by Nicknaem** [Darkhax-Minecraft/BotanyPots#186]
I think it should have configuration in what time should plants grow, in ticks or millisecons, I would like to see them grow quicky 😃

**Comment by DeadTrapsDevelopment** [comment]
Hi ^^
here is a example how to do this ^^

https://docs.blamejared.com/1.16/en/mods/BotanyPots/BotanyPots/

**Comment by DeadTrapsDevelopment** [comment]
here u find all crops
https://github.com/Darkhax-Minecraft/BotanyPots/tree/1.16.5/src/main/resources/data

as example:
`
import mods.botanypots.ZenCrop;

val crops = <recipetype:botanypots:crop>;
val inferium = crops.getCrop("mysticalagriculture:crops/inferium");

inferium.setGrowthTicks(200);
`
u get the cropid from the site above.
id is everytime
modfolder:crops/jsonname
mysticalagriculture:crops/inferium

**Comment by Nicknaem** [comment]
thanks
