### ISSUE TITLE
Draconic revolution

### ISSUE THREAD

**Issue by daviblro** [Darkhax-Minecraft/BotanyPots#187]
Does botany pots not have compat for draconic revolution seeds added by mystical agriculture? Idk if it's a bug or not that I can't place the seeds on the pot

**Comment by Darkhax** [comment]
There likely is not support yet. For a seed to be planted it needs to be registered via the datapack system. I normally do this on my end but there are many types of seeds from mods and their addons that have not been added yet.

**Comment by daviblro** [comment]
Got it, hoping for some day when it can be added then! Great mod

**Comment by Darkhax** [comment]
Reopening this issue as I use them to keep track of what needs to be done.

**Comment by Darkhax** [comment]
Thanks for the report, this should now be resolved thanks to the help of ModernGamingWorld. If there are any issues with the latest update let me know.

**Comment by ngoetti** [comment]
@Darkhax I think this issue can be closed.
