### ISSUE TITLE
[Feature Request] Waterlogged Pots

### ISSUE THREAD

**Issue by Boolyman** [Darkhax-Minecraft/BotanyPots#188]
Would it be possible to enable the Botany Pots to be waterlogged?  When used in sunken structures or farms, they create an odd air pocket.  I am creating Rustic Waters 2, and was going to use these extensively.

**Comment by Darkhax** [comment]
Hello, I will look into adding this.

**Comment by Boolyman** [comment]
Thank you!

**Comment by ngoetti** [comment]
It looks like water logging is now working. #195
