### ISSUE TITLE
[Request][Simple Farming] Add Habanero to the crop definition of Pepper

### ISSUE THREAD

**Issue by Nahkranoth0** [Darkhax-Minecraft/BotanyPots#190]
Taking into account that the Pepper has a rare chance of dropping Habanero when farming it, wouldn't it be possible to change the crop definition in Botany Pots to reflect that?

I don't know the exact chance that it has of dropping said Habanero instead of the Pepper. 
Something between 0.1% - 0.5% in crop definition

**Comment by ngoetti** [comment]
I could not find Habanero in the Mod Pam's HarvestCraft.

**Comment by Darkhax** [comment]
@ngoetti They're asking about Simple Farming. It looks to be registered under the ID `simplefarming:habanero`.
