### ISSUE TITLE
Latest Version of Botany Pots has several crops missing 

### ISSUE THREAD

**Issue by fatpally** [Darkhax-Minecraft/BotanyPots#191]
Current Mystical Agriculture Version: 1.16.5-4.2.3
Current Botany Pots Version: 7.1.24
The following cannot be planted other than making a custom script in craft tweaker
Pig Iron
Marble
Apatite
Slimesteel
Tinkers Bronze
Ruby Seed
Sapphire Seed
Rose Gold
Cobalt
Manyllun
Queen Slime
Hepatizon
Nitro Seeds
Basalt
Limestone

**Comment by ngoetti** [comment]
Fluorite Seeds from Mystical Agriculture do not work as well

**Comment by amouranthtoo** [comment]
also Nitro Crystal seeds from POWAH

**Comment by amouranthtoo** [comment]
Sorry i mean Mystical Agriculture*

**Comment by etherealgears** [comment]
Just wanted to add that Greenheart Saplings from Tinker's Construct do not appear to be growable with the latest version of the mod. The other Tinker's saplings, i.e. the Skyroot and the Nether and End slime island saplings, all work, so I'm assuming this is an oversight and meant to be growable.

**Comment by ngoetti** [comment]
@Darkhax If you commit message of 429280abfa6d8f5564ae5c509d832677cbde1006 is to be believed this should all be fixed and the issue can be closed.
