### ISSUE TITLE
Biomes O' Plenty no longer has an ash block

### ISSUE THREAD

**Issue by jeremiahwinsley** [Darkhax-Minecraft/BotanyPots#194]
This recipe errors because ash blocks do not exist anymore.

https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.16.5/src/main/resources/data/biomesoplenty/recipes/soil/ash.json

**Comment by Darkhax** [comment]
Thanks for the report, this should now be resolved thanks to the help of ModernGamingWorld. If there are any issues with the latest update let me know.
