### ISSUE TITLE
disable harvesting grown crops

### ISSUE THREAD

**Issue by Nicknaem** [Darkhax-Minecraft/BotanyPots#197]
can I somehow disable harvesting grown crops? I just want them for decorations, one solution is to just lower the chance yeld, but is it possible to also disable harvesting animation?
![Animation](https://user-images.githubusercontent.com/55950404/137600408-3b2a2dac-3414-4040-81e2-50f4a631a71b.gif)

**Comment by Darkhax** [comment]
Hello, it's not currently possible but I am open to adding something in the future. What is your exact use case here? Are you a player looking to add this to your own world, someone building an adventure map, or someone trying to balance out a modpack?

**Comment by Nicknaem** [comment]
ok, I set yeld chance to 0 for all crops, and I'm satisified with this, I am just making my modpack, and I wanted botany pots just for decorations, not for farming purposes, thanks for response anyway.
