### ISSUE TITLE
Some Mystical Agriculture recipes require wrong soil tiers

### ISSUE THREAD

**Issue by Sunekaer** [Darkhax-Minecraft/BotanyPots#199]
Nearly all of the Botany Pot recipes for Mystical Agriculture require that the seed require the same tier or higher of soil - Inferium for tier 1, Prudentium for tier 2, Tertium for tier 3, Imperium for tier 4, Supremium for tier 5, and Insanium for tier 6.

However, the following recipes are requiring the wrong tier:

    Sky Stone (tier 3) requires Imperium (tier 4)
    Certus Quartz (tier 3) requires Imperium (tier 4)
    Fluorite (tier 4) accepts Prudentium (tier 2)
    Netherite (tier 5) accepts Imperium (tier 4)
    Nether Star (tier 6) accepts Supremium (tier 5)
    Dragon Egg (tier 6) accepts Supremium (tier 5)

Additionally, some recipes are even allowing ordinary soil types:

    Energized Steel (tier 4)
    Blazing Crystal (tier 4)
    Niotic Crystal (tier 5)
    Spirited Crystal (tier 5)
    Uraninite (tier 5)
    Blizz (tier 3)
    Blitz (tier 3)
    Basalz (tier 3)
    Signalum (tier 4)
    Lumium (tier 4)
    Enderium (tier 5)

Oddly, a few of the mixed up seeds are also ones that aren't even craftable in the first place:

    Iridium (tier 5) accepts Prudentium (tier 2)
    Platinum (tier 5) accepts Prudentium (tier 2)

**Comment by quietust** [comment]
The "not even craftable" remark was specific to the modpack in which this issue was discovered, where they presumably got auto-disabled due to lack of ingredients.

**Comment by Darkhax** [comment]
Thanks, I will look more into this issue. Is it possible that the seeds have different tiers when enabled through different mods? Are there any mods or addons changing these tiers?

**Comment by Raidobw2** [comment]
Hey, thanks for the reply. Yes @Sunekaer is using addon mods to MA.
MA's version: `MysticalAgriculture-1.16.5-4.2.5.jar`
Mystical Aggraditions: `MysticalAgradditions-1.16.5-4.2.3.jar`
MysticalCustomization-1.16.5-2.1.6.jar: `MysticalCustomization-1.16.5-2.1.6.jar`
+Other mods to make the seeds show up I'm assuming, Thermal, Powah, AE2, Mekanism etc.

There's only 2 additional jsons for MysticalCustomization:
`crystal_shards.json` under `config/mysticalcustomization/crops`
```
{
    "name": "Crystal Shards",
    "type": "resource",
    "tier": "mysticalagriculture:3",
    "ingredient": {
        "item": "betterendforge:crystal_shards"
    },
    "color": "7410a9",
    "textures": {
        "flower": "mysticalagriculture:block/flower_rock",
        "essence": "mysticalagriculture:item/essence_gem"
    }
}
```
`electrotine.json` under `config/mysticalcustomization/crops`
```
{
    "name": "Electrotine",
    "type": "resource",
    "tier": "mysticalagriculture:2",
    "ingredient": {
        "item": "projectred-core:electrotine_dust"
    },
    "color": "0b537b",
    "textures": {
        "flower": "mysticalagriculture:block/flower_dust",
        "essence": "mysticalagriculture:item/essence_dust"
    }
}
```
We also have a script for our botany pots under `kubejs/server_scripts`, called `recipes.botanypots.js`. It's a scripting mod that emulates a datapack, to inject additional content.
Contents of that script: https://paste.feed-the-beast.com/view/63383125
I think this adds some recipes that weren't in-game? I'm not 100% sure.

Sunekaer mostly configured this, he'll be able to tell you more info about it, at least most of it if not all the relevant info should already be here to speed up his reply.
Thanks for taking the time to look into this!

**Comment by quietust** [comment]
In Mystical Agriculture, Fluorite is defined as using `CropTier.FOUR` (i.e. Imperium):
https://github.com/BlakeBr0/MysticalAgriculture/blob/1.16/src/main/java/com/blakebr0/mysticalagriculture/lib/ModCrops.java#L137

However, BotanyPots is only demanding Prudentium (i.e. tier 2):
https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.16.5/src/main/resources/data/mysticalagriculture/recipes/crops/fluorite.json#L17

The situation seems to be similar for the other seeds.

> We also have a script for our botany pots under kubejs/server_scripts, called recipes.botanypots.js. It's a scripting mod that emulates a datapack, to inject additional content.
> Contents of that script: https://paste.feed-the-beast.com/view/63383125
> I think this adds some recipes that weren't in-game? I'm not 100% sure.

Most of those appear to be the same recipes reported as missing in #191.

**Comment by ngoetti** [comment]
@quietust Even Iridium (Tier 5) Seeds grow on regular farmland. As far as I am aware the different categories of the mystical agriculture farmland only provide a speedup. So actually botany pots should remove all tier limitations, because they are not present in the mystical agriculture itself.

**Comment by ngoetti** [comment]
> Nearly all of the Botany Pot recipes for Mystical Agriculture require that the seed require the same tier or higher of soil - Inferium for tier 1, Prudentium for tier 2, Tertium for tier 3, Imperium for tier 4, Supremium for tier 5, and Insanium for tier 6.

This is not the case with the regular version of mystical agriculture 1.16.5. Or am I completely wrong?
@Sunekaer

**Comment by Darkhax** [comment]
This should now be fixed @Sunekaer. Sorry for the long delay, I've had a lot of other stuff to deal with and this issue is pretty annoying to debug because it involves a dozen or so different mods and addons to addons. Initially I was worried this may be an issue where ModA platinum is tier X and ModB platinum is tier Y but it looks like these were all the result of human error when writing the datapack files. Mystical Agriculture support should be more reliable when I finally port this up to 1.18+.

@ngoetti I sometimes like to take creative liberty when it comes to balancing seeds that can be grown by these pots. For example vanilla requires farmland for most of their crops but I allow them to grow on dirt and even grass. With mystical agriculture I decided that gating the seeds based on soil tier would be a good way to balance out how overpowered automating their crops can be.
