### ISSUE TITLE
Allow Waterlogging of Botany Pots

### ISSUE THREAD

**Issue by WenXin20** [Darkhax-Minecraft/BotanyPots#2]
If waterlogging of pots is added, this could add a new decoration feature and maybe other functions, such as growing seaweed, kelp, coral or other water plants only underwater.

**Comment by Darkhax** [comment]
Water soil was added in https://github.com/Darkhax-Minecraft/BotanyPots/commit/a194d41785326f8ec5615967c4047ffd0a7bd96e

Vanilla water crops were added in https://github.com/Darkhax-Minecraft/BotanyPots/commit/899d1a535ffd2f7dfaab57b092b1507b0316e336
