### ISSUE TITLE
Soil/Seeds disappearing from Pots

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/BotanyPots#20]
I would like to re-open issue #16 

Forge 31.1.36
Botanypot 2.0.5

Only Forge, Jei, MysticalAgriculture and Botany pots mods used

Botany pot ontop of a chest, supremium farmland and spider seeds growing in pot
Save and quit game
Close Minecraft completely
Re-run launcher, Run Minecraft and Load previous world
Soil/Seeds from Botany pots have disappeared
Default configs used

[Latest Log](https://pastebin.com/iC2e2mKU) (Line 185 is interesting) says Block at Pos 0 0 0, which are not the coords of the botany pot

**Comment by DoCharlcate** [comment]
Same issue on 1.15.2, Forge 31.1.36. Happens with 'Simple Farming' also.

**Comment by Darkhax** [comment]
#16 was fixed by updating to 2.0.6. You're still on 2.0.5.

**Comment by ghost** [comment]
my bad. what a dumbass, sorry
