### ISSUE TITLE
Change growth time

### ISSUE THREAD

**Issue by Pedro-phd** [Darkhax-Minecraft/BotanyPots#200]
Add simple command for chage growth time.
or command for kubejs ?

**Comment by Darkhax** [comment]
There are ways to do this with datapacks, or a CraftTweaker option if you want to script it. 
```zenscript
// Gets the crop registry
var crops = <recipetype:botanypots:crop>;

// Loop through each cropId in the crop registry
for cropId in crops.recipeMap {

    // This code is ran once for each crop ID in the game.
    
    // Get the crop data for the current ID, then multiply it's growth
    // time to be 2x the original value.
    crops.getCrop(cropId).growthTicks *= 2;
}
```

KubeJS will not be receiving any first party support from me.

**Comment by Pedro-phd** [comment]
@Darkhax  Hello, this command not work, would you have another solution?
![image](https://user-images.githubusercontent.com/36482675/140752246-91853bb4-2792-4681-b1f6-a4d73c2fc780.png)

**Comment by jacklollz2** [comment]
Make this a config file setting instead.
