### ISSUE TITLE
Nitro Crystal Seed Can't be placed in botany

### ISSUE THREAD

**Issue by amouranthtoo** [Darkhax-Minecraft/BotanyPots#202]
For Some odd reason whenever i try to put a nitro crystal seed in the pot it just won't work i looked at recipes but nothing so im not sure
![image](https://user-images.githubusercontent.com/45043402/141984520-e1a875cb-c70e-4570-a8b5-5b5890d3a75b.png)

**Comment by Darkhax** [comment]
Thanks for the report, this should now be resolved thanks to the help of ModernGamingWorld. If there are any issues with the latest update let me know.

**Comment by amouranthtoo** [comment]
> 
> 
> Thanks for the report, this should now be resolved thanks to the help of ModernGamingWorld. If there are any issues with the latest update let me know.

yes there is an issue w/ the latest update and its making the nitro crystal seeds drop nitro crystals instead of essence

**Comment by Darkhax** [comment]
Could you give me the ID for the essense?
