### ISSUE TITLE
Datapack has no effect

### ISSUE THREAD

**Issue by YiyangWilliam** [Darkhax-Minecraft/BotanyPots#204]
I tested it first in creation mode with no problems, but when I used the datapack in survival mode after restarting my computer it didn't work. Is there something wrong with my datapack?

mc version:1.16.5Forge
[BOT-main.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/7558577/BOT-main.zip)

**Comment by Darkhax** [comment]
There are a few issues with your datapack.

1) If the datapack is a ZIP pack the initial BOT-main folder is not allowed and will prevent loading. If it's a folder pack and zipped for GitHub then it's fine.

2) The pack only contains a custom dirt soil. If you're trying to override the existing dirt soil the file needs to be in the exact same folder as the pre-existing one. `data/botanypots/recipes/soil/dirt.json` vs `data/botanypots/recipes/dirt.json`

3) The format of your dirt.json file seems to be using outdated properties. It should look like [this](https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.16.5/src/main/resources/data/botanypots/recipes/soil/dirt.json).
