### ISSUE TITLE
Can't the data package be removed or overwritten with the recipe?

### ISSUE THREAD

**Issue by joe-vettek** [Darkhax-Minecraft/BotanyPots#205]
I modified the crop formula of the mod, but it seems to be useless. Although two types are displayed in jei, the previous content is still output.

**Comment by Darkhax** [comment]
The best way to remove crops is through CraftTweaker or any other tool with the option to remove recipes. If you insist on using datapacks, the new recipe file must have the exact same ID as the recipe provided by the mod. Like all things in datapacks the ID is taken from the filepath so copying that should be enough.

**Comment by joe-vettek** [comment]
Thanks.
