### ISSUE TITLE
The potato recipe has broken

### ISSUE THREAD

**Issue by AKTheKnight** [Darkhax-Minecraft/BotanyPots#21]
Second time this has happened, but I don't know how I've done it.
The potato recipe apparently needs nothing?

Can't now put potatoes into a pot.

Fixed with a server restart.

Latest.log is here https://pste.ch/axuceretor.sql but as this was after midnight it's not the full log, I can get that if needed.

![image](https://user-images.githubusercontent.com/7502848/79029024-752fed80-7b8a-11ea-94f8-09cbd43790e0.png)

**Comment by Darkhax** [comment]
The hastebin is empty. Please post versions of Forge, Bookshelf, and Botany Pots.

**Comment by Rushmead** [comment]
The hastebin isn't empty for me. 

Forge version: 1.15.2-31.1.36 
Bookshelf: 5.3.9
Botany Pots: 2.0.5

**Comment by Darkhax** [comment]
That's really weird, I still can't see it. Anyhow you're using an outdated version of Botany Pots. 2.0.6 fixes a few issues with how recipes are synced to the client.

**Comment by Darkhax** [comment]
I will assume this issue is fixed, however I have heard from other devs that there may be a related race condition with JEI when connecting to servers so I wouldn't be surprised if this pops up again eventually.
