### ISSUE TITLE
[Question] Fabric Port planed?

### ISSUE THREAD

**Issue by MSandro** [Darkhax-Minecraft/BotanyPots#210]
Hello, 
I really like your mod, but I've switched to Fabric since MC 1.16.5. Now I have noticed that the Bookshelf API has been ported to Fabric. Would it therefore be possible that you also bring your Mod Botany Pots to Fabric?

On Fabric there is one alternative named "Plant In A Jar" but it is buggy and it has no much options to configure it.

I would appreciate that very much. Many Thanks.

**Comment by Darkhax** [comment]
Yes, virtually all of my mods will support Fabric starting with MC 1.18.1. This will be done using https://github.com/jaredlll08/MultiLoader-Template which we have invested a lot of development time on.
