### ISSUE TITLE
Compatibility Request - Refined Storage Importers/Extra Storage Advanced Importers

### ISSUE THREAD

**Issue by AerosAtar** [Darkhax-Minecraft/BotanyPots#212]
Currently pots and hopper pots do not work if connected directly to Importers - items are not pulled out of regular pots, and hopper pots cannot push items either. It would be great if this could be addressed, though I am unsure how realistic the request is.

**Comment by Darkhax** [comment]
Thanks for this request. I would like for these blocks to be compatible, however there are some weird design challenges that prevent this from working. I will continue looking into this issue however I can not promise it will get fixed any time soon, if at all.

**Comment by Darkhax** [comment]
This issue has been fixed in the 1.18.2 alpha, however it will not be realistic to backport these fixes to 1.16.5.
