### ISSUE TITLE
Latest version no longer works with mystical agriculture farmland

### ISSUE THREAD

**Issue by RuneOracle** [Darkhax-Minecraft/BotanyPots#215]

**Comment by RuneOracle** [comment]
![2022-02-19_22 01 45](https://user-images.githubusercontent.com/75599640/154826718-4c23d3c2-7d39-4fdd-af0e-90f12fa4dcf0.png)

sorry if this isn't an issue with BP, r-clicking on the pots with mystical agri soil just places it on top of them like this.

**Comment by Darkhax** [comment]
Are you playing with a 3rd party modpack? Several packs intentionally remove Botany Pot support for certain mods like Mystical Agriculture.

**Comment by RuneOracle** [comment]
Enigmatica 6 but I don't remember if it was included by default (I know mystic agri was not included, I manually added it) things from botania and other crop/soil related mods work just fine, the only issue is with Mystic

**Comment by RuneOracle** [comment]
So I've just tested in a new pack with only mystic and botanypots, and they work normally, my apologies about that, no idea what controls that config sadly

But on the bright side there is no real issue
