### ISSUE TITLE
Bamboo growth time is very slow

### ISSUE THREAD

**Issue by Smibbix** [Darkhax-Minecraft/BotanyPots#216]
For some reason, bamboo takes a full 1:30 to grow by default. Meanwhile, sugarcane only takes 40 seconds. This doesn't seem to align with how fast they actually grow in game, since bamboo is the fasted growing plant in Minecraft, and certainly grows faster than sugarcane.

**Comment by ngoetti** [comment]
I checked the Minecraft Wiki and it seems that you are right. Therefore I propose to reduce the ticks from 1800 to 600. Anything way lower then that might be to overpowered.

**Comment by Darkhax** [comment]
Thanks to ngoetti, the growth time is now 600 ticks in the next update. Players may need to replant their bamboo for the change to take effect.
