### ISSUE TITLE
Ore trees

### ISSUE THREAD

**Issue by JustAWh1teFox** [Darkhax-Minecraft/BotanyPots#218]
Is there any way to combine botany pots with the ore trees mod??

**Comment by ngoetti** [comment]
If one were to add the recipes to src/main/resources/data/ it should be possible. I might do it myself however my knowledge of minecraft modding is severely limited.

**Comment by ngoetti** [comment]
It seems regular saplings are not (or no longer) supported. Maybe @Darkhax doesn't want to support the ore tree saplings either.

**Comment by Darkhax** [comment]
@ngoetti Sapplings/Trees are part of the [Botany Trees](https://www.curseforge.com/minecraft/mc-mods/botany-trees) addon. I don't believe Ore Trees has support yet in either mod.

**Comment by ngoetti** [comment]
Okey I'm currently working on integrating it into BotanyTrees.

**Comment by ngoetti** [comment]
If you accept these new soil types I can implement the rest

**Comment by PhweeDev** [comment]
This has been added in both BotanyPots (ore soils) and BotanyTrees (Ore Trees)

**Comment by Darkhax** [comment]
Thanks
