### ISSUE TITLE
[Suggestion] Seeds to go through different stages of growing

### ISSUE THREAD

**Issue by ngoetti** [Darkhax-Minecraft/BotanyPots#223]
Currently the seeds just get bigger while growing. Their age is set to a fixed value in "properties": { "age": 7 } // usually 7
Would it be a performance killer to have them go through the stages 1 to 7?

**Comment by Darkhax** [comment]
Thanks for the suggestion. There would be no performance impact here. This was an initially planned feature however I put it on the back burner while working over a good way to implement this. Currently the system involves optionally defining an array of render states and giving each state an equal share of the render time. For example if 5 states are defined each state would show for 20% of the growth cycle. The main hold up is considering if the transition ranges should be configurable and if I should make deeper changes to the system to automate this on the back end. This will probably make it into the 1.18/1.19 update.

**Comment by ngoetti** [comment]
>  The main hold up is considering if the transition ranges should be configurable
I don't think this needs to be configurable. Having them go through all the stages they normally would is good enough and should save time while implementing and configuring.

**Comment by Darkhax** [comment]
This feature is now available in the new 1.18.2 version.
