### ISSUE TITLE
[Request] Port to 1.18.2

### ISSUE THREAD

**Issue by TacoSauceDev** [Darkhax-Minecraft/BotanyPots#225]
Playing ATM7 and finding myself really missing BotanyPots. Really love your mod. I would love to see this ported to 1.18

If there is some way for me to help make this happen, please let me know. I have experience with Java, but not with Gradle.

**Comment by TacoSauceDev** [comment]
I pulled the code down and having been learning how to use gradle, but it appears that you utilize hwyla which is not being supported for future ports. Do you know which one you want to use in the future? Looks like there are a couple of options. If you can comment back with which you'd like to move forward with, I can try my best to get a PR for you.

**Comment by Darkhax** [comment]
@TacoSauceDev Thanks for trying to help, however I don't think I am open to accepting this type of PR at this time. The 1.18.2 update is not using the majority of the 1.16.5 codebase. The reasoning for this has already been discussed in depth on Discord but here is a short summary.

- Migrating to a MultiLoader project. This is a new way of developing mods that allows build targets for multiple mod loaders. Bookshelf has already moved to this, but several big features such as recipe types, tile entities, networking, and inventories have been missing.
- Rewrite pot implementation to improve support for various item transport mods that do not properly expose an inventory interface. Many pipe mods in particular only pull from inventories and do not expect things to push into them.
- Add growth conditions to the crop spec.
- Rework the interface to include a GUI that includes more information for players. The hope is to cut back on issue reports from players of modpacks that completely change how the mod works.
- Loader-neutral recipe conditions to help with mod support. Stuff like disable recipe X if mod Y is not present.

I also plan to re-validate most of the mod support files to correct many inconsistencies and standardize things in general.

**Comment by TacoSauceDev** [comment]
@Darkhax  No worries, thanks for the reply. Please let me know if you could use help in some way in the future. I am a devops engineer and would be happy to lend a hand.

**Comment by Darkhax** [comment]
@TacoSauceDev Thanks for the offer to help. Once I have a beta available I would appreciate bug testing and feedback from the community, and help adding and reviewing support for other MC mods.
