### ISSUE TITLE
Issue with custom crops via datapacks [1.16.5]

### ISSUE THREAD

**Issue by BlindTheBoundDemon** [Darkhax-Minecraft/BotanyPots#230]
I've been trying to add a couple of farmable items that in my opinion should be farmable in the pots but for some reason, i can't get the soil to work.
[MissingBotanyCrops.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/9219040/MissingBotanyCrops.zip)

**Comment by Darkhax** [comment]
It looks like you're using an outdated reference for the soil. The soil should look like [this](https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.16.5/src/main/resources/data/botanypots/recipes/soil/dirt.json). 

Always check the game log for issues related to your datapack files first.
