### ISSUE TITLE
Server won't load [1.18.2-Alpha]

### ISSUE THREAD

**Issue by SGZ-Creations** [Darkhax-Minecraft/BotanyPots#232]
Can't locate sounds and causes server to not boot/load completely

Here's the log where it happens:
[latest.log](https://github.com/Darkhax-Minecraft/BotanyPots/files/9275288/latest.log)

**Comment by Darkhax** [comment]
You have Bookshelf 13.2.41 but at least 13.2.47 is required.

**Comment by SGZ-Creations** [comment]
Well could u make so it downloaded reqired mod? Some mods does that so was wondering if u could as well

**Comment by Darkhax** [comment]
It is against the CurseForge TOS for a mod to download other mods. The CurseForge launcher, or capable 3rd party launchers can already download dependencies for you automatically.

**Comment by SGZ-Creations** [comment]
Not download a random mod but required mod like a core mod thing that yours uses.

If i understood it as it was your mod as well

**Comment by Darkhax** [comment]
Yes, it is my mod. However that is still against their TOS. Automatically downloading other mods would allow a mod to install malware, or farm fake downloads to increase their download count so CurseForge does not allow this.
