### ISSUE TITLE
Mystical Agriculture compatibility issue (1.18.2)

### ISSUE THREAD

**Issue by haydo75332** [Darkhax-Minecraft/BotanyPots#233]
you can't add Mystical Agricultures tiered farmland to the pots

**Comment by Darkhax** [comment]
The 1.18.2 version has no support for modded crops or soils. This is a known limitation of the alpha and not an issue.

**Comment by haydo75332** [comment]
ok 
Is there any plan to add it in future

**Comment by Darkhax** [comment]
Yes mod support will come later. The point of the current alpha is to gather testing and feedback on the new inventory system and other mechanical changes in the mod.
