### ISSUE TITLE
Mystical Agriculture

### ISSUE THREAD

**Issue by RhagVreal** [Darkhax-Minecraft/BotanyPots#235]
Can't place Mystical Agriculture Farmland in Hopper-Botany-Pot 
Can't place Mystical Agriculture Seed's in Hopper-Botany-Pot 
Minecraft Version 1.18.2

**Comment by Darkhax** [comment]
The 1.18.2 version has no support for modded crops or soils. This is a known limitation of the alpha and not an issue.
