### ISSUE TITLE
Pots do not work with mystical agriculture on 1.18

### ISSUE THREAD

**Issue by ellipse12** [Darkhax-Minecraft/BotanyPots#238]
none of the seeds that I have tried in mystical agriculture are able to be put into a pot.

**Comment by Darkhax** [comment]
The 1.18.2 version of the mod is in alpha and does not support any modded crops or soils at this time. They will slowly be added back soon.

**Comment by ellipse12** [comment]
oh ok! sorry I did not realize that.

**Comment by Darkhax** [comment]
A new alpha now includes support.
