### ISSUE TITLE
Compatibility request -(Hexerei/Ars Noveau)

### ISSUE THREAD

**Issue by Atlas-The-Rock** [Darkhax-Minecraft/BotanyPots#239]
I know you must get these 1000 times a day lol but when you get the chance please add support for both Hexerei and Ars Noveau crops. There are not a ton so it shouldn't be a herculean task like mystical agriculture.

Thank you for your time!

**Comment by Darkhax** [comment]
Thanks for the request. I will look into this.

**Comment by Darkhax** [comment]
I am not very familiar with either mod. Could you please let me know if I am missing any crops?

## Hexerei

### Crops
- Mandrake
- Belladona
- Mugwort
- Yellow Dock Bush
- Sage

### Trees
- Mahogany
- Willow

## Ars Nouveau

### Crops
- Sourceberry


### Trees
- Cascading Archwood
- Vexing Archwood
- Flourishing Archwood
- Blazing Archwood

**Comment by Atlas-The-Rock** [comment]
There's a magebloom seed in ars noveau that is missing but other than that
it should be it

**Comment by Darkhax** [comment]
Thanks for letting me know. All of the crops have been added to Botany Pots. I don't include trees in this mod so they will be added to the TODO list for Botany Trees. Updating Bookshelf will also be required for this to work properly.

**Comment by Atlas-The-Rock** [comment]
Great job man! You should be proud! Botany pots brings the experience of
minecraft to a whole new level, I'm not sure it the botania mystical
flowers work again after the 1.18.2 jump but I will check into that today.
Thanks again for the quick response and adding those crops!

**Comment by Atlas-The-Rock** [comment]
ah on testing it looks like while mugwort and the non seed plant from the
hexerei crops work, sage seeds do not, same with the magebloom seeds from
ars nouveau. i'm also not able to get any of the colored botania plants to
work.

**Comment by Darkhax** [comment]
@Atlas-The-Rock Do the items say seed item when you hover over them in the pot?
![image](https://user-images.githubusercontent.com/2250798/188132871-abb0e97f-4353-431f-b47c-cbde2eb1c649.png)

**Comment by Atlas-The-Rock** [comment]
no it doesnt actually

**Comment by Darkhax** [comment]
That's very strange. They are working fine for me with just the required mods installed. Could you please check your log file for any errors referencing these crops?
