### ISSUE TITLE
Integration with Croptopia

### ISSUE THREAD

**Issue by jlaine3333** [Darkhax-Minecraft/BotanyPots#240]
Request for integration with Croptopia's crops. They are all vanilla-derived so it shouldn't be too much trouble.

**Comment by Darkhax** [comment]
Thanks for the request. I will look into adding support soon.

**Comment by Jadziyah** [comment]
Came here to also request Croptopia compatibility! Was surprised I couldn't use them for crop growth in ATM8

**Comment by Darkhax** [comment]
This should now be fully available for 1.19.2 and 1.18.2.
