### ISSUE TITLE
Compat. Request for Oh The Biomes You go

### ISSUE THREAD

**Issue by Ayria** [Darkhax-Minecraft/BotanyPots#241]
As stated in title.

Also do you plan to make this and Botany Trees one mod instead of updating the other?

Thanks so much for all the work!

**Comment by Darkhax** [comment]
Hello, the data system used by this mod changed in 1.18.2 to accommodate simultaneous forge/fabric/quilt releases so mod compat is being slowly added back. 

Botany Trees is intentionally a separate mod because Botany Pots is not intended to clash or step on the toes of Bonsai Trees.

**Comment by Ayria** [comment]
Understood! Thanks for getting back to me on this, I appreciate it.

**Comment by Jadziyah** [comment]
Also came here to request this! Oh the Biomes is becoming the biome mod of choice for the newer MC modpacks/versions

**Comment by Darkhax** [comment]
Support for BYG has been added. There was a LOT of soils and foliage so let me know if I missed anything. 

- **1.18.2** - Use 8.0.18 or newer
- **1.19.2** - Use 9.0.13 or newer
