### ISSUE TITLE
Water/lava not rendering fluid in 1.19.2

### ISSUE THREAD

**Issue by CrazyRandomzZ** [Darkhax-Minecraft/BotanyPots#243]
putting a water bucket or lava bucket into a pot does not render the fluid.

might have something to do with the changed made to minecraft:water and minecraft:lava as they can no longer be spawned in.

**Comment by Darkhax** [comment]
I've tested this feature on Forge and Fabric 1.19.2 and could not recreate the issue you are describing. Please ensure you are using the latest versions and if it still does not work there may be interference from other mods like Optifine.

**Comment by Jack-McKalling** [comment]
For the record, I'm reproducing this in a mod pack with the exact same version as in a "vanilla" setup, where it doesn't reproduce.
So this issue _must_ be related to another mod.
