### ISSUE TITLE
BotanyPots with ATM7to the sky?

### ISSUE THREAD

**Issue by OceanRift** [Darkhax-Minecraft/BotanyPots#244]
Possible to add integration with ATM7tothesky? 
New version prevent to place seeds in hopper pots + growing time is insane.

**Comment by Darkhax** [comment]
ATM7tothesky is a modpack. Any changes to custom crops they add themselves, or the balance of growth time is up to them to configure. If there are any specific mods that need support please open up a request for those mods.
