### ISSUE TITLE
Pixelmon Datapack assistance (1.16.5)

### ISSUE THREAD

**Issue by InfinitysDaughter** [Darkhax-Minecraft/BotanyPots#246]
Lets just say I'm an idiot and anyone seeing this, check you spelled everything right. @w@

**Comment by InfinitysDaughter** [comment]
Oh my Lord I did the same dang thing the last time I asked for help!

In my defense that was 2 years ago... but still. >.<

**Comment by Darkhax** [comment]
I guess I can close this. If you still need help let me know.
