### ISSUE TITLE
[1.19.2] Fix Farmer's Delight Compatibility

### ISSUE THREAD

**Issue by HalcyonSeas73** [Darkhax-Minecraft/BotanyPots#248]
Botany Pots version: 9.0.3
Bookshelf version: 16.1.5
Forge version: 43.1.1
Minecraft version: 1.19.2

- Farmer's Delight's Rice Pancles and Onions don't presently work properly. Onions work similar to vanilla's Carrots, whereas the Rice Pancles require water for growth.
- Brown and Red Mushroom Colonies both require Rich Soil (exclusively); depending on harvest stage/level, they drop between 1 and 5 mushrooms.
- The tooltip for Rich Soil indicates seeds grow _slower_, rather than faster. Functionally, it works, so I imagine this is just an error with the tooltip.

**Comment by Darkhax** [comment]
Thanks for opening this issue. This issue is related to Farmers Delight having outdated compatibility files on their end. I've sent a PR to them that will fix these issues. https://github.com/vectorwing/FarmersDelight/pull/552
