### ISSUE TITLE
Can't make new crop (datapack 1.19.2)

### ISSUE THREAD

**Issue by uiuinPP** [Darkhax-Minecraft/BotanyPots#249]
I'm using: 
- minecraft 1.19.2 
- forge 43.1.25 
- BotanyPots 9.0.3
- Bookshelf 16.1.5 

Custom soil is working properly but i can use any custom crops. 

data/betterdrop/recipes/ and i have 2 files here

test.json (working) https://i.imgfly.me/jkqLoy.png
`{
  "type": "botanypots:soil",
  "input": {
    "item": "minecraft:white_wool"
  },
  "display": {
    "block": "minecraft:white_wool"
  },
  "categories": ["dirt"],
  "ticks": 250
}`

oaksapling.json (not working) https://i.imgfly.me/jkqzT1.png
`{
  "type": "botanypots:crop",
  "seed": {
    "item": "minecraft:bedrock"
  },
  "categories":["dirt"],
  "growthTicks": 1,
  "growthModifier": 3.5,
  "display": {
    "block": "minecraft:bedrock"
  },
  "results": [
    {
      "chance": 0.75,
      "output": {
        "item": "minecraft:bedrock"
      },
      "minRolls": 1,
      "maxRolls": 1
    }
  ]
}`

**Comment by Darkhax** [comment]
The information on the wiki has not been updated to account for the new alpha versions. The format is very similar but a few things have changed. Please reference the files on GitHub for a valid example.

[dirt.json](https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.19.2/Common/src/main/resources/data/botanypots/recipes/minecraft/soil/dirt.json)

[wheat.json](https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.19.2/Common/src/main/resources/data/botanypots/recipes/minecraft/crop/wheat.json)

Here is a brief summary of a few of the changes.
- New display state system that is more flexible and allows rotations and transitions over time.
- results is now called drops
- if min and max are both 1 you can just omit them.
