### ISSUE TITLE
[Fabric 1.18.2] growthModifier is inverted

### ISSUE THREAD

**Issue by faeldray** [Darkhax-Minecraft/BotanyPots#251]
Version: BotanyPots-Fabric-1.18.2-8.0.12.jar

The growthModifier on soil appears to be inverted in regards to what the tooltip lists. For example, if I set a soil to a growthModifier of 2.0, the tooltip says that it should be 2 times faster but it's actually 2 times slower. But if I change it to 0.1, the tooltip says it's 10 times slower, but in reality it's 10 times faster.

It appears as though this isn't isolated to just this version, because #248 references the same issue as well.

**Comment by OceanRift** [comment]
Also for forge 1.18.2!

**Comment by Darkhax** [comment]
Thanks for letting me know. This issue has been fixed in the latest 1.18.2 alpha. A new 1.19.2 alpha will be out soon.
