### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by OceanRift** [Darkhax-Minecraft/BotanyPots#253]
Hello, 
Add please auto support magical soil + ATM seeds please

**Comment by Darkhax** [comment]
Hello, if a modpack is adding new seeds to the game themselves, they should probably be the ones to add botany pots support as well. If "ATM Seeds" is being distributed as a standalone mod I can look into adding support.

**Comment by OceanRift** [comment]
I added a few crops by myself, but I don't know how to make it Display texture like growing seed in Pot, but it works in Tier 6 soil

**Comment by Darkhax** [comment]
The mod uses blockstates for rendering and will use the model of that block. You can not specify a specific texture.
