### ISSUE TITLE
Botany Pots Progress Bar

### ISSUE THREAD

**Issue by IsaiahMM** [Darkhax-Minecraft/BotanyPots#255]
The Botany Pots in ATM 8 aren't showing the progress meter they used to show previously. Not sure if this was an intended change or not but it would be nice to be able to see the plants growth percentage again.

**Comment by Darkhax** [comment]
Does the bar show at all or is it completely missing?

**Comment by IsaiahMM** [comment]
> Does the bar show at all or is it completely missing?

The progress bar shows up but does not move from 0%

**Comment by Darkhax** [comment]
Thanks, this should be fixed in 9.0.5
