### ISSUE TITLE
Mod Support: Chococraft

### ISSUE THREAD

**Issue by SethWilliamson** [Darkhax-Minecraft/BotanyPots#262]
[https://www.curseforge.com/minecraft/mc-mods/chococraft](https://www.curseforge.com/minecraft/mc-mods/chococraft)

chococraft:gysahl_green_seeds:
- 100% chance to drop chococraft:gysahl_green
- 15% chance to also drop chococraft:loverly_gysahl_green
- 5% chance to also drop chococraft:gold_gysahl

Notes:
- Drop chances taken from in-game documentation (chocopedia)
- Total growth time seems roughly equal to wheat
- Growth stages: 0%, 25%, 50%, 75%, 100%

**Comment by Darkhax** [comment]
Thanks for the request. I will look into adding this.
