### ISSUE TITLE
Mod Support: Farmer's Delight

### ISSUE THREAD

**Issue by InkDragon** [Darkhax-Minecraft/BotanyPots#263]
Would love to see support for [Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight). Same idea as pam's harvest craft but smaller over all.

**Comment by darkdex52** [comment]
With some update at some point Rich Soil from Farmer's Delight mod got broken. It used to really speed up growth in the pots and some update later it turned it into 0.1x speed instead.

**Comment by Darkhax** [comment]
This is an issue with Farmer's Delight. I've already sent them the fix they just haven't released that update yet. https://github.com/vectorwing/FarmersDelight/pull/552
