### ISSUE TITLE
[1.14.4] Druidcraft crop datapack

### ISSUE THREAD

**Issue by noobanidus** [Darkhax-Minecraft/BotanyPots#27]
I'm not sure how best to implement this into your system but I keep forgetting about it, so [here](https://cdn.discordapp.com/attachments/570536138234658827/673166509077430312/druidcraft-botanypots-compat.zip) is a compat datapack for Druidcraft!

**Comment by Darkhax** [comment]
This has been added in https://github.com/Darkhax-Minecraft/BotanyPots/commit/bc534f58c7878e9c643c14990d971f23b1635f80 Thanks.
