### ISSUE TITLE
[1.18.2] Soils and their effects seem inverted

### ISSUE THREAD

**Issue by Scheigster** [Darkhax-Minecraft/BotanyPots#274]
I opened [an issue](https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1727) on FTB issue tracker but it was closed, asking me to open an issue here. The following is a copy of the issue (note that this is regarding Stoneblock 3 on 1.18.2):

Thanks to the recent addition of the Botany Pots' JEI integration, we can now see that it is possible to use different soil in the pots. But they seem to be configured in the opposite way.

Let's take the seed as an example:

1. Soil used : Dirt. 
Grow Time: 1 minute.

![image](https://user-images.githubusercontent.com/7931135/200305134-f9c8c89f-ea60-4962-8b7a-dcd7f25d1cb4.png)

2. Soil used : Farmer's Delight's Rich Soil. 
Grow Time: 10 minutes (x10).

![image](https://user-images.githubusercontent.com/7931135/200305469-3047aaf0-6dce-4ec9-ae00-797b99453a42.png)

For all seeds that I checked (seed, sugar cane, saplings), the best soil is Dirt while all the other soils takes longer to grow.

**Comment by Darkhax** [comment]
Which version of farmers delight are you using? They recently had a bug where the rich soil was defined as 10% (-90%) of the normal growth time rather than 110% (+10%) of the normal growth time. This bug has been fixed but some packs are shipping outdated versions still.

**Comment by Sunekaer** [comment]
FarmersDelight-1.18.2-1.2.0.jar
BotanyPots-Forge-1.18.2-8.0.16.jar

**Comment by Sunekaer** [comment]
Seems like the growth modifier has inverted, so it makes recipes with better dirt take longer than being faster

**Comment by Darkhax** [comment]
@Sunekaer This is not the case, it is only Farmers Delight which has broken soils and crops as well. You can learn more about the issue [here](https://github.com/vectorwing/FarmersDelight/pull/552). Someone told me they released an update a while ago but I don't see it on CurseForge yet so everyone is still waiting for them to release it. You can use the PR I submitted to them as a datapack to temporarily fix the issue.

**Comment by Sunekaer** [comment]
Oh interesting thanks
