### ISSUE TITLE
If pot produces nothing, progression stops at 100%

### ISSUE THREAD

**Issue by Nachtflame** [Darkhax-Minecraft/BotanyPots#275]
BotanyPots-Forge-1.19.2-9.0.11
forge-43.1.43
Minecraft 1.19.2

As per the title.  If all outputs are less than `"chance": <1.0`, and the pot has a cycle that results in no item being produced, the progress stops at 100% until recipe items are reset (removed/re-inserted).

Very Niche problem I know, but thought it should be reported.

**Comment by Darkhax** [comment]
Thanks for letting me know. We caught this on 1.18.2 a few days a go and a fix is pending for 1.19.2.

**Comment by Darkhax** [comment]
Sorry for the delay, I thought this was fixed already but it looks like I forgot to push the 1.19.2 fix. It's now been fixed in 9.0.16.
