### ISSUE TITLE
Add option to remove the growing animation

### ISSUE THREAD

**Issue by GeraldGat** [Darkhax-Minecraft/BotanyPots#28]
Hello,
I think it could be a really good idea to give the option to remove the growing effect of plants. In fact, a lot of pot can have a big impact on the fps of the game.

**Comment by Darkhax** [comment]
Hello, 

I've done several tests for the performance of the botany pot to see where they could be improved. The animation of the crop growing has virtually 0 impact on the game and removing it or turning it off will not give you better FPS. 

In my tests I used commands to place down 400 botany pots and compared them to 400 signs, chests, and other similar blocks in the vanilla game. These tests showed that the botany pots are extremely efficient for what they do, and has slightly less impact on FPS than a vanilla oak sign with the words "Hello World" on it. 

Placing a lot of botany pots definitely does have an impact on FPS, however the impact is no worse than many common vanilla blocks such as a sign.
