### ISSUE TITLE
Can't plant vanilla crops

### ISSUE THREAD

**Issue by Lapislazulitacos** [Darkhax-Minecraft/BotanyPots#282]
BotanyPots-Forge-1.18.2-8.0.19
1.18.2-forge-40.1.85
Minecraft 1.18.2

As per the title, I can't plant wheat seeds, carrots, or potatoes in the botany pots. I can put all the soils as well as water in the pots, and pumpkins, melons, mushrooms, flowers, and sugar cane all work fine.

**Comment by PhweeDev** [comment]
I've not been able to recreate this using forge 40.1.84. Try downgrading your Forge one version and see if that fixes it.

**Comment by Darkhax** [comment]
If you are playing on a premade modpack it's possible that the pack author has removed or disabled certain crops. If that's not the case then please update the mod and the libraries and try again. If the issue still persists please load the game, enter a world, try to plant the crop, and then upload your latest.log file from the game folder so I can review it for any conflicts or errors. 

Here are the versions I would recommend for your Minecraft version.
- Forge: 40.1.86
- Bookshelf: 13.2.51
- Botany Pots: 8.0.20

**Comment by Lapislazulitacos** [comment]
I updated Forge and the mods to the versions you recommended, and the problem was resolved. Thank you for your help.
