### ISSUE TITLE
Can't plant Onion and Rice in botany pots and Rich Soil not working

### ISSUE THREAD

**Issue by Urias0** [Darkhax-Minecraft/BotanyPots#289]
Hey , so i'm on the last 1.19.2 version ( BotanyPots-Forge-1.19.2-9.0.19 ) and i cannot plant onion and rice in the pots pretty sure it worked in 1.16.5 , if you need any more information ask me

**Comment by Darkhax** [comment]
Hello, thanks for opening this issue. The issue is on Farmers Delight's end however I have already submitted a fix to them. We are waiting for them to release an update. You can learn more here https://github.com/vectorwing/FarmersDelight/pull/552
