### ISSUE TITLE
Adding Features from Graden Stuff

### ISSUE THREAD

**Issue by heidefinnischen** [Darkhax-Minecraft/BotanyPots#29]
This is just a suggestion because I really liked Garden Stuff but the mod seems abandoned.
Would it be possible to add features like the modular flower pots? 

I really liked those flower pots on the right.

![external-content duckduckgo](https://user-images.githubusercontent.com/58484745/80861346-58a94180-8c6e-11ea-8d6b-32f78c1a346c.jpg)

**Comment by Darkhax** [comment]
Hello, 

This is a good request however I am happy with where the mod is currently and don't want to take features from other mods.
