### ISSUE TITLE
[1.19.2] Moss Block shows Moss Carpet texture

### ISSUE THREAD

**Issue by HalcyonSeas73** [Darkhax-Minecraft/BotanyPots#290]
![image](https://user-images.githubusercontent.com/84727791/209667744-305bcc92-fc39-4cf5-8163-bae4003d4a36.png)

Drops are still Moss Block, but the growth appears to be a Moss Carpet.

**Comment by Darkhax** [comment]
Fixed via https://github.com/Darkhax-Minecraft/BotanyPots/commit/030cf577f1e93c377b4dba3281cb1d47c69d044f
