### ISSUE TITLE
Add support for "The One Probe"

### ISSUE THREAD

**Issue by bookerthegeek** [Darkhax-Minecraft/BotanyPots#292]
### Heyo!

You have made a wonderful mod and I have been playing with it for a while now and have only one valid complaint, which is the lack of integration with [The One Probe](https://github.com/McJtyMods/TheOneProbe). 

Without this, all we see is the progression of us breaking the block, and not the progress of the growing in the pot. Not a massive usability issue but still something that would be nice to fix from a usability standpoint.

The API for adding compatibility can be found [HERE](https://github.com/McJtyMods/TheOneProbe/tree/master/src/main/java/mcjty/theoneprobe/api).

Thank you for taking the time to consider this an issue and have a great day!

**Comment by Darkhax** [comment]
Hello, The One Probe is already supported on Forge for MC 1.16.5, 1.18.2, and 1.19.2. Are you looking for Fabric support?

**Comment by bookerthegeek** [comment]
> One Probe is already supported on Forge for MC 1.16.5, 1.18.

I'll double check and get version numbers.

**Comment by AbacusOperator** [comment]
> Hello, The One Probe is already supported on Forge for MC 1.16.5, 1.18.2, and 1.19.2. Are you looking for Fabric support?

It technically does, but it doesn't show progress percentage of plant growth in 1.18.2 Forge at least.

**Comment by LarcekGiglamesh** [comment]
running:
• BotanyPots-Forge-1.18.2-8.0.24
• theoneprobe-1.18-5.1.2
• latest Forge 1.18.2 - 40.2.1

i can confirm the botany pots grow and be harvested just fine, but the % through TheOneProbe stays at 0%

**Comment by Darkhax** [comment]
The progress being stuck at 0% has now been fixed.
