### ISSUE TITLE
1.16.5 MA not working with botany pots

### ISSUE THREAD

**Issue by DragonS9** [Darkhax-Minecraft/BotanyPots#294]
Unable to place netherite seeds into the pot, tried using every type of farmland block and still not able to place netherite into the pot

**Comment by Darkhax** [comment]
I've just downloaded these mods and confirmed they still work as intended. In the base mod you will need to use an insanium tier farmland. If you are playing on a 3rd party modpack it is possible that the pack makers have changed the recipe to something else.

My test used the following versions.
- Forge 36.2.34
- BotanyPots 7.1.39
- Mystical Agriculture 4.2.6

![image](https://user-images.githubusercontent.com/2250798/210541463-578d5f8e-2fb8-4128-942c-6fee4bfa7bfb.png)
