### ISSUE TITLE
Mod - allthemodium seeds 

### ISSUE THREAD

**Issue by VictorMC22** [Darkhax-Minecraft/BotanyPots#295]
Hi!
I would like to ask for help.
I'm trying to add the unobtainium seed recipe and all the seeds of this mod in the botany pots by craftTweaker, but I can't. what do I do?

**Comment by Darkhax** [comment]
CraftTweaker support is only available on 1.16.5 right now. You can learn more about it [here](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/CraftTweaker-Support). It will come to 1.18.2 and 1.19.2/3/4 eventually but there is no ETA.
