### ISSUE TITLE
Suggestion: Farmer's Delight

### ISSUE THREAD

**Issue by ZAPGam1ng** [Darkhax-Minecraft/BotanyPots#296]
Can you add support for [Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight) please

**Comment by Darkhax** [comment]
Farmer's delight is already supported but they have some incorrect support files in their mod. I've helped them fix this last October but they haven't released the update yet. I've included a workaround for this in Botany Pots 9.0.23 for 1.19.2. A 1.18.2 workaround will be released soon.
