### ISSUE TITLE
[1.19.2] Farmer's Delight Soil

### ISSUE THREAD

**Issue by Draskh** [Darkhax-Minecraft/BotanyPots#297]
Farmer's Delight's Rich Soil currently have a value of 0.1 speed modifier and 0.25 for its respective farmland.
I guess it should be 1.1 and 1.25 as Rich Soil is better version of dirt.

**Comment by Darkhax** [comment]
This is a bug in Farmers Delight. I've helped them fix it last October but they haven't released an update yet. I've included a workaround for this in Botany Pots 9.0.23.
