### ISSUE TITLE
Crash on Fabric 1.19.2

### ISSUE THREAD

**Issue by pokesmells** [Darkhax-Minecraft/BotanyPots#299]
Crashed when trying to enter a world, or making a new one.

[crash-2023-01-20_11.53.45-client.txt](https://github.com/Darkhax-Minecraft/BotanyPots/files/10468860/crash-2023-01-20_11.53.45-client.txt)

**Comment by Darkhax** [comment]
Hello, a fix to this was uploaded a few hours before your issue was submitted. Could you please update bookshelf to [16.2.17](https://www.curseforge.com/minecraft/mc-mods/bookshelf/files/4354813) and let me know if this resolves your issue.

**Comment by pokesmells** [comment]
Ah yes, completely fixed. 

Thanks boss, you're the best.
