### ISSUE TITLE
Compatibilidad con Ferroustry

### ISSUE THREAD

**Issue by ArturilloD** [Darkhax-Minecraft/BotanyPots#30]
Buenas, siento si no se debe notificar por aquí, soy nuevo y no tengo mucha idea todavía de como funciona esto.
La cuestión es que me gustaría si pudieras añadir soporte con "Ferroustry" (https://www.curseforge.com/minecraft/mc-mods/ferroustry) a "Botany Pots" por favor, creo que sería un añadido interesante.
Un saludo y gracias de antemano.

**Comment by Darkhax** [comment]
Hola, no puedo hablar español, así que estoy usando el traductor de Google.

El mod Botany Pot solo admite flores y plantas, pero no árboles. Mi mod se basa en el mod Bonsai Trees y no quiero superponerme con él.

https://www.curseforge.com/minecraft/mc-mods/bonsai-trees

**Comment by ArturilloD** [comment]
I understand, thank you very much. If it is not a lot of trouble, could you
help me to make it compatible, please? It is for personal use only. Again,
thank you very much.
