### ISSUE TITLE
Crash with Expanded Delight 1.19.2

### ISSUE THREAD

**Issue by Gamerbolts** [Darkhax-Minecraft/BotanyPots#302]
Hello I am having some issues with the newest version of your mod, it is crashing with Expanded Delight. I have the following mods installed:

Bookshelf - 16.2.17
BotanyPots - 9.0.24
Expanded Delight - 0.2.5.1
Fabric API 0.73.0
Farmer's Delight - 1.3.9

The crash happens when having these mods installed and trying to create a new world. Here are the following log and crash log files. Any help is appreciated. I have also reported this to the Expanded Delight mod dev. Thank you!

[crash-2023-01-24_16.19.03-client.txt](https://github.com/ianm1647/expandeddelight/files/10494510/crash-2023-01-24_16.19.03-client.txt)
[latest.log](https://github.com/ianm1647/expandeddelight/files/10494512/latest.log)

**Comment by Darkhax** [comment]
Hello, the logs don't clearly point to anything wrong with my mods. Please try updating to 9.0.26 and see if that fixed anything.

**Comment by DJChaos42** [comment]
Having an identical issue in 1.20.1. Tested on a brand new Quilt instance with all mods updated to their most recent versions.

[crash-2023-07-28_10.55.49-client.txt](https://github.com/Darkhax-Minecraft/BotanyPots/files/12196742/crash-2023-07-28_10.55.49-client.txt)
[latest.log](https://github.com/Darkhax-Minecraft/BotanyPots/files/12196739/latest.log)

Testing Environment:

Minecraft Version: 1.20.1
Modloader: Quilt 0.20.0-beta4
Launcher: ATLauncher 3.4.30.0

Installed mods:
Bookshelf-Fabric-1.20.1-20.0.2
BotanyPots-Fabric-1.20.1-13.0.2
Expanded Delight 0.3.0.1
Farmer's Delight 1.4.1 - 1.20-1.20.1
QFAPI 7.0.6 and QSL 7.0.6+0.85.0-1.20.1
