### ISSUE TITLE
Hopper botany pot causing drastic lag while putting on top of a hopper

### ISSUE THREAD

**Issue by hokomili** [Darkhax-Minecraft/BotanyPots#303]
### Version:
BotanyPots-Fabric-1.19.2-9.0.22
### Modpack:
All of Fabric 6 - 1.3.0
### Issue:
It happens in a very specific case where the hopper have one non-full stack of one product in the hopper pot while the hopper pot is full of another product (the more thing in hopper pot, the more lag)
Btw this is built in server but the server wasn't lag at all.
### How to reproduce:
this is the hopper pot
![2023-02-09_21 47 40](https://user-images.githubusercontent.com/28939939/217837795-8f300b74-1bc0-4ad5-aa97-41e013f56cd7.png)
this is hopper below it (the seeds are not full)
![2023-02-09_21 48 18](https://user-images.githubusercontent.com/28939939/217837811-53893a5b-efba-47cb-bb98-26ea2288c3d7.png)
With 4 set of this it can easily drop to 0-2 fps
![2023-02-09_21 44 11](https://user-images.githubusercontent.com/28939939/217840536-2a5088f8-3ad8-41f7-bbc6-2a8023b768a3.png)
I crashed and cannot enter the server after I built the 5th set.

**Comment by Darkhax** [comment]
Thank you for bringing this to my attention. I believe I have identified and fixed the issue. Could you please try this alpha build and let me know if it works for you? I am fairly confident this will fix your FPS issues although there may be other bugs that have been introduced. Here is a ZIP file, GitHub doesn't like JAR files so you will need to unzip it. 

[BotanyPots-Fabric-1.19.2-9.1.0+beta.1-unzip-me.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/10700719/BotanyPots-Fabric-1.19.2-9.1.0%2Bbeta.1-unzip-me.zip)

**Comment by hokomili** [comment]
It works perfectly fine! Or at least it didn't cause anything noticeable during my normal use case.

**Comment by Darkhax** [comment]
Thanks for confirming. New builds will be published to CurseForge soon for everyone to use.
