### ISSUE TITLE
Massive lag for 8x8x1 filled to the brim hopper pot farm

### ISSUE THREAD

**Issue by Oslypsis** [Darkhax-Minecraft/BotanyPots#305]
MC 1.19.2
Botany Pots Fabric-1.19.2-9.0.22
Botany Trees Fabric-1.19.2-5.0.4
Fabric 36.1.32
Default config settings

I'm not sure if this is just my fault and I apologize if it is, but I left my pots (8x8x1, growing almost all kinds of plantables) running in the spawn chunks for probably over 5 hours (yes I know now, bad idea) while I went looking for allays in my large biome world. I had clearly set up a sub-par storage system (10 double chests with 68 hoppers) and upon returning, when I got near spawn, my game froze (twice in the same location, and I suspect it was the edge of where the pots were loading in) and I (only once) had to force quit. Upon reopening, my fps were nothing but a slideshow until I was able to break the hopper pots. Specifically breaking the pots themselves drastically reduced lag. I didn't waste time trying to open them to take items out as I was worried I'd crash again, so I don't have info on how that would affect the behavior of this issue.

I'd suggest the hopper pots to either stop trying to harvest, or to count and delete the same number of harvested items from the GUI (essentially just replacing items with the same number of the same items) immediately after checking and seeing that the GUI is filled.
So say each GUI slot can hold 64 seeds or 64 wheat for example, and when each slot has 64 of seeds/wheat but only 1 slot has less than 64 seeds, no more wheat should be available for processing to harvest. Just seeds, so the slot fills to 64 without the extra processing for the wheat drops, and once a stack of items is in each slot all processing of harvesting is paused until the hopper pot is emptied (sorry if that was confusing).

**Comment by Darkhax** [comment]
This issue was fixed in 9.0.27, please update the mod to the latest version and try again.
