### ISSUE TITLE
[Suggestion] Botany pots being affected by seasons

### ISSUE THREAD

**Issue by DevilsBride98** [Darkhax-Minecraft/BotanyPots#306]
Not sure if it is posible or if its implemented trough config, but it would be nice for winter/summer/autum/spring crops in botany pots to only grow in their respective season, adding this way a bit more dificulty.

Thank you :)

**Comment by Darkhax** [comment]
Thanks for the suggestion. The ground work for an addon to add this feature is there but it's not something I am personally interested in implementing myself.
