### ISSUE TITLE
1.18.2 - Hopper pots stuck on last phase of growth

### ISSUE THREAD

**Issue by JarekZagorski** [Darkhax-Minecraft/BotanyPots#309]
My hopper pots are stuck on the last stage of growth after coming back from the nether. Only way I found to fix that is to destroy and replace the pot. Reloading chunks / world didn't help.
Version: 1.18.2
My mod list:

- appleskin-forge-mc1.18.2-2.4.1.jar
- Architects-Palette-1.18.2-1.2.0.jar
- architectury-4.11.89-forge.jar
- AutoRegLib-1.7-53.jar
- badpackets-forge-0.1.3.jar
- balm-3.2.5.jar
- Bookshelf-Forge-1.18.2-13.2.52.jar
- Botania-1.18.2-435.jar
- BotanyPots-Forge-1.18.2-8.1.27.jar
- cloth-config-6.4.90-forge.jar
- comforts-forge-1.18.2-5.0.0.6.jar
- Compressium-1.4.2-build.9+mc1.18.2.jar
- configured-2.0.0-1.18.2.jar
- Controlling-forge-1.18.2-9.0+22.jar
- corpse-1.18.2-1.0.2.jar
- craftingtweaks-forge-1.18.2-14.0.4.jar
- create-1.18.2-0.5.0.i.jar
- createaddition-1.18.2-20230221a.jar
- Cucumber-1.18.2-5.1.3.jar
- curios-forge-1.18.2-5.0.9.0.jar
- DarkUtilities-Forge-1.18.2-10.1.6.jar
- easy_piglins-1.18.2-1.0.4.jar
- easy_villagers-1.18.2-1.0.11.jar
- elevatorid-1.18.2-1.8.4.jar
- FastWorkbench-1.18.2-6.1.1.jar
- flywheel-forge-1.18.2-0.6.8.a.jar
- gardenofglass-1.10.jar
- Highlighter-1.18.1-1.1.2.jar
- Iceberg-1.18.2-forge-1.0.49.jar
- .index
- ironfurnaces-1.18.2-3.3.3.jar
- Jade-1.18.2-forge-5.2.6.jar
- jei-1.18.2-forge-10.2.1.1002.jar
- JER-Integration-3.3.2.jar
- JustEnoughResources-1.18.2-0.14.1.171.jar
- LegendaryTooltips-1.18.2-1.3.1.jar
- mininggadgets-1.11.1.jar
- MouseTweaks-forge-mc1.18-2.21.jar
- NaturesCompass-1.18.2-1.9.7-forge.jar
- oculus-1.4.3a.jar
- Patchouli-1.18.2-71.1.jar
- Placebo-1.18.2-6.6.6.jar
- polymorph-forge-1.18.2-0.46.jar
- Powah-3.0.7.jar
- Prism-1.18.2-1.0.1.jar
- Quark-3.2-358.jar
- refinedstorage-1.10.5.jar
- refinedstorageaddons-0.8.2.jar
- rsrequestify-2.2.0.jar
- rubidium-0.5.4.jar
- selene-1.18.2-1.17.9.jar
- shutupexperimentalsettings-1.0.5.jar
- sophisticatedbackpacks-1.18.2-3.18.40.777.jar
- sophisticatedbackpacksvh-1.18.2-1.0.5.13.jar
- sophisticatedcore-1.18.2-0.5.37.202.jar
- StorageDrawers-1.18.2-10.2.1.jar
- supermartijn642configlib-1.1.6-forge-mc1.18.jar
- supermartijn642corelib-1.1.4-forge-mc1.18.jar
- supplementaries-1.18.2-1.5.16.jar
- Terralith_v2.2.3.jar
- torchmaster-18.1.0.jar
- trade-cycling-forge-1.18.2-1.0.2.jar
- trashcans-1.0.17a-forge-mc1.18.jar
- twigs-1.1.4-patch4+1.18.2-forge.jar
- waystones-forge-1.18.2-10.2.0.jar
- Xaeros_Minimap_23.2.0_Forge_1.18.2.jar
- XaerosWorldMap_1.29.2_Forge_1.18.2.jar

Any help appreciated

**Comment by Hojosa** [comment]
[broken_hopperPots.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/11069117/broken_hopperPots.zip)
Here a copy of my test world, only with Bookshelf, Botany Pots, and Botany Trees. Placed down some Pots, left world, rejoined -> broke them.

**Comment by Darkhax** [comment]
Thank you for providing additional details. This issue should now be fixed. Existing pots that were broken will start working again automatically but any progress they had will be lost.
