### ISSUE TITLE
Add possibility to have flowers higher than 1 block

### ISSUE THREAD

**Issue by Rogrom73** [Darkhax-Minecraft/BotanyPots#31]
Is it possible to have flowers growing the same size as original one (rose for example) and to put more than one flower in the same pot when small ones?

**Comment by Darkhax** [comment]
Yes, this is possible to add. I already have a basic version of this working and will upload an update soon.

**Comment by Darkhax** [comment]
The latest alpha now supports defining multiple block states for crops. [Example file for datapackers](https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.15.2/src/main/resources/data/botanypots/recipes/crops/lilac.json).

![unknown](https://user-images.githubusercontent.com/2250798/81249315-d625d680-900d-11ea-8c31-a87f5f380aad.png)

**Comment by Rogrom73** [comment]
Working fine.

Thanks for the job :)

Le jeu. 7 mai 2020 à 05:02, Tyler Hancock <notifications@github.com> a
écrit :
