### ISSUE TITLE
[1.19.4] MIssing JEI Pot shortcut

### ISSUE THREAD

**Issue by ffuentesm** [Darkhax-Minecraft/BotanyPots#312]
As you can see, the Pot is missing that shortcut on the left of JEI that let you see all items that can be used with a pot. 
You can only check individual items at the moment. 
![image](https://user-images.githubusercontent.com/44974827/230752749-d4da88ac-fdcb-40c0-b1de-85ece2c8f5a1.png)

![image](https://user-images.githubusercontent.com/44974827/230752744-881638a7-312b-4512-a040-5cbb289ea70b.png)

**Comment by Darkhax** [comment]
I've been wanting to add this for a while, but JEI has a crash when there are too many variants. You can track progress on that issue here: https://github.com/mezz/JustEnoughItems/issues/3183

**Comment by Darkhax** [comment]
This has been added to 1.19.4. Make sure you have the latest version of JEI installed. 
![image](https://user-images.githubusercontent.com/2250798/235388349-01f52a52-d271-4c8c-a85c-86496d86410b.png)

**Comment by ffuentesm** [comment]
Lol, Those are A LOT of pot options.

**Comment by Darkhax** [comment]
Yep, that's why it was crashing JEI lol. I hope in the future we will have the option to do a single item that cycles through all the options, but at least this works now.

**Comment by ffuentesm** [comment]
JEI is great and with many compatibilities, but REI does have a more pleasant crafting UI with how they have scrollable rows of crafting options instead of tabs that you need to move through.
