### ISSUE TITLE
Simple Farming not working

### ISSUE THREAD

**Issue by Malus-Lupo** [Darkhax-Minecraft/BotanyPots#313]
Minecraft 1.19.2
Forge 42.2.8
Botanypots 9.0.30
Simple Farming 2.0.4
Can not plant any simple farming crops into botany pots on server or single player.

**Comment by Darkhax** [comment]
Thanks for letting me know. The berry bushes, marshmallow root, and cumin seeds should all still work. Looks like they changed the IDs for the other crops so I will need to push an update.

**Comment by Malus-Lupo** [comment]
Oh no prob, that would be amazing! Thanks.

**Comment by Darkhax** [comment]
This should be fixed in 9.0.31. Thanks again for reporting.
