### ISSUE TITLE
[Suggestion] EMI support

### ISSUE THREAD

**Issue by Nataly171** [Darkhax-Minecraft/BotanyPots#314]
[EMI](https://modrinth.com/mod/emi) is a wonderful JEI/REI alternative that's gaining a lot of popularity, and I'd love to see this mod be able to support it.

**Comment by Darkhax** [comment]
Thanks for the request. Unfortunately I only have time to maintain JEI support, not even REI is supported. If someone else would like to open a Pull Request or make an addon they are more than welcome to.
