### ISSUE TITLE
Mod support: Blockus

### ISSUE THREAD

**Issue by nick-zh** [Darkhax-Minecraft/BotanyPots#315]
[Blockus](https://github.com/Brandcraf06/Blockus) has a white oak sapling (maybe more), it would be cool to add support for those as well 😄

**Comment by Darkhax** [comment]
Thanks for the request, I will look into the mod to see what can be supported. Keep in mind that trees and saplings are covered by the [Botany Trees](https://www.curseforge.com/minecraft/mc-mods/botany-trees) addon, so tree related support will be uploaded there.

**Comment by nick-zh** [comment]
@Darkhax ah cool thx, good to know regarding the trees, i was trying to find an example so i could maybe open a pr myself, but didn't find too much tree stuff here 😄

**Comment by Darkhax** [comment]
The Rainbow Rose has been added to Botany Pots 1.19.2/1.19.4, and the White Rose has been added to Botany Trees for 1.19.2/1.19.4

**Comment by nick-zh** [comment]
@Darkhax many thx 🚀
