### ISSUE TITLE
Farmer's Delight Rice doesn't work

### ISSUE THREAD

**Issue by moshner** [Darkhax-Minecraft/BotanyPots#317]
Describe the bug
Rice should be a valid crop with water but it isn't allowing me to place it in water. Not sure if pack bug or mod bug.

To Reproduce

1. Put down botany pot
2. Add a bucket of water to the bottom slot
3. Try to add a farmersdesight:rice to the top slot
4. Doesn't add to the pot

Expected behavior
Adds the item to the pot and makes more rice

Additional context
https://github.com/Darkhax-Minecraft/BotanyPots/blob/45dac0b24eafa3eb446cbae66ea7ab12cbc881d4/Common/src/main/resources/data/botanypots/recipes/farmersdelight/crop/rice.json

This has been confirmed in an experience with just the required mods.

**Comment by Darkhax** [comment]
Which version of Minecraft and Botany Pots are you using?

**Comment by moshner** [comment]
Botany Pots: Fabric 1-19.2-9.0.31
Minecraft: 1.19.2
Farmer's Delight: Fabric 1.19.X-1.3.9

**Comment by Darkhax** [comment]
Ah I see, the Fabric version of this mod is by a different author and has different block and item IDs so it is not supported yet.

**Comment by Darkhax** [comment]
After looking into this issue and speaking with some of the devs, it looks like the Fabric version of Farmers Delight did not use the correct IDs for rice. They fixed this in the 1.3.10 update. 

https://github.com/newhoryzon/farmers-delight-fabric/issues/110
