### ISSUE TITLE
Compatibility with Serene Seasons

### ISSUE THREAD

**Issue by OxiiGiin1** [Darkhax-Minecraft/BotanyPots#318]
It would be great to have it where crops can't grow out of season like in serene seasons, or have it to where they get a huge negative modifier so they grow much slower.

**Comment by Darkhax** [comment]
Thanks for the suggestion. This has come up a few times but I am not very interested in adding those types of limitations into the mod. The mod is meant to bypass those types of restrictions, for example you can grow crops in non-farmland soils and without a nearby water block. The mod has an API that would allow a 3rd party addon to impose these this type of restriction though so anyone is able to make an addon for this if they would like.
