### ISSUE TITLE
couldn't put bamboo on the pot

### ISSUE THREAD

**Issue by ZR-00** [Darkhax-Minecraft/BotanyPots#32]
i tried things when i then realized that among all the crop that exist on vanilla, you cant use bamboo??
tried sand, dirt, even gravel, nope, it didnt do anything

![2020-05-08_22 46 16](https://user-images.githubusercontent.com/64331654/81422965-f379b280-917d-11ea-9cdf-d25a48588c88.png)

**Comment by Darkhax** [comment]
Bamboo was intentionally excluded but was recently added to the 1.15.2 beta.

**Comment by ZR-00** [comment]
> Bamboo was intentionally excluded but was recently added to the 1.15.2 beta.

"BotanyPots-1.15.2-2.0.17.jar" ?

**Comment by Darkhax** [comment]
Yes that is the correct version. It should work on any sand or dirt soil.
