### ISSUE TITLE
Inconsistent behavior?

### ISSUE THREAD

**Issue by Daniel-ags** [Darkhax-Minecraft/BotanyPots#320]
So, i've been having a problem which i can only describe as "inconsistent". I'm using BotanyPots alongside Pipez and for some reason, in my singleplayer modpack, no pipe is able to connect to the BotanyPots (i made sure they were all hopping). But in the modpack that i play multiplayer, it also doesn't work when i go to singleplayer, but when i play on my multiplayer server, the pipez connect to the pots!

I already posted an issue in the Pipez GitHub and just got referenced to a previous issue that just talked about the expected behaviour, where Botany Pots need a inventory bellow them to output. Can anybody help me?

I'm playing minecraft 1.19.2 and i tried all the available versions of both Botany Pots and Pipez, with the same inconsistencies.

If screenshots/videos can help to diagnose it, no problem in providing btw.

**Comment by vadcx** [comment]
The first paragraph of where and how it happens/when it doesn't is indeed confusing, it would help if you wrote down the three distinct setups clearly, where it does (not) work. Screenshots would likely help yourself in writing all this down.

**Comment by Darkhax** [comment]
Both the pipez dev and myself were able to verify that it works as intended. https://github.com/henkelmax/pipez/issues/175
