### ISSUE TITLE
Could you add a config option to disable crop growing animations?

### ISSUE THREAD

**Issue by minecraftdudette** [Darkhax-Minecraft/BotanyPots#323]

**Comment by Xiarno** [comment]
Agreed.
Having a big number of Botany Pots causes a high amount of lag due to the animation. A config to disable it would be welcomed.

**Comment by Darkhax** [comment]
No, this is not how rendering works. The crop inside the pot is rendered at a certain scale and the animation simply changes that scale over time to give the appearance that the crop is growing. A scale factor is already required to make the crop fit within the bounds of the pot so rendering the crop at 1x scale has the same render times as rendering the pot with the animated scaling. I added this as an option in 1.16.5 to prove the point and there was no demonstrable difference so the option was removed to keep the code maintainable and to allow additional rendering options for crops.

**Comment by minecraftdudette** [comment]
Thanks for the answer and explanation!
