### ISSUE TITLE
[1.19.2][ATM8+] Game Crashes with attached Crashlog

### ISSUE THREAD

**Issue by Th3C0D3R** [Darkhax-Minecraft/BotanyPots#324]
I encoutner crashed after half an hour of playing.
Crashlog says its about ticking the block entity at a specific location (Botany Hopper Pot containing Tertium Farmland and Iron Seed from Mystical Agriculture)
For testing (if its BotanyPots or MA), I replace the seed with normal MC seed, but maybe you can see the problem within the log.

If its MA, I will close the Issue.

BotanyPots Version: BotanyPots-Forge-1.19.2-9.0.33
MysticalAgriculture Version: MysticalAgriculture-1.19.2-6.0.10

[crash-2023-06-26_10.00.15-server.txt](https://github.com/Darkhax-Minecraft/BotanyPots/files/11865944/crash-2023-06-26_10.00.15-server.txt)

**Comment by Th3C0D3R** [comment]
ok seams to be fine so far. will replace it with Iron Seed again and maybe relocate it to exclude locational problems

**Comment by Th3C0D3R** [comment]
ok happend again with a different Botany Hopper Pot, but I was on exploration thousand of blocks away
Log:
[crash-2023-06-26_12.43.22-server.txt](https://github.com/Darkhax-Minecraft/BotanyPots/files/11867623/crash-2023-06-26_12.43.22-server.txt)

**Comment by Darkhax** [comment]
This appears to be an issue with KubeJS. The modpack likely has issues with their scripts or KubeJS has broken botany pot support.

**Comment by Th3C0D3R** [comment]
yeah I looked into the problem and found a hint on their discord server to just delete the `botanyPots.js` inside the `kubejs/startup_scripts` folder
Will close here as its nothing to do with BotanyPots itself
