### ISSUE TITLE
Add support for Mystical Agriculture: Refabricated crops

### ISSUE THREAD

**Issue by Bernhard---H** [Darkhax-Minecraft/BotanyPots#326]
Would it be possible to add support for crops of this mod: https://github.com/AlexSa1000/MysticalAgriculture-Refabricated

While playing All of Fabric 6, I found that these 2 seeds won't be accepted:

* from Industrial Revolution mod: [Nikolite Dust](https://github.com/AlexSa1000/MysticalAgriculture-Refabricated/blob/1.19.2/src/main/java/com/alex/mysticalagriculture/lib/ModCrops.java#L108)
* from Modern Industrialization mod: [Antimony Ingot](https://github.com/AlexSa1000/MysticalAgriculture-Refabricated/blob/1.19.2/src/main/java/com/alex/mysticalagriculture/lib/ModCrops.java#L111)

Original Issue: https://github.com/TeamAOF/All-of-Fabric-6/issues/281

**Edit:** I posted *workaround* configs in the linked issue above, which should fix this issue

**Comment by Darkhax** [comment]
Thanks for letting me know about this. These missing crops should now be supported in 9.0.38 for MC 1.19.2.
