### ISSUE TITLE
Able to place, unable to plant (with KubeJS)

### ISSUE THREAD

**Issue by godofmangos** [Darkhax-Minecraft/BotanyPots#328]
This is a development to the issue, I have found that the problem is with the KubeJS mod and/or its different versions for other existing mods such as create or blood magic. How does one fix the errors given from the mod in relation to botany pots?

Hello, my issue is a strange one. I am able to craft, interact, pickup, place, and properly see botany pots of every color and type, but no matter where I am when i place them or what soil is put in, i can never seem to actually place a plant/flower into the pot. As you can see in the picture, I play with mods, and if you would like the full mod list I linked it to this ask, which you should be able to access. I just really want this mod to work, its so useful and versatile. thank you for reading. [https://file.io/GNN4wAsoyE3K](url)
![unable to plant](https://github.com/Darkhax-Minecraft/BotanyPots/assets/139590836/f28ff5c3-e46f-40da-b3a4-0c2faed2497e)

**Comment by godofmangos** [comment]
I should mention that this is in version 1.16.5, forge version 36.2.39

**Comment by Darkhax** [comment]
Issues with KubeJS should be reported to the author of that mod. KubeJS is not officially supported and it sounds like a broken script in your pack is preventing the crop recipes from loading.
