### ISSUE TITLE
Add a GUI toggle to auto-export (push) items out. [Botany Hopper pots cause huge lag when the chest below it is full.]

### ISSUE THREAD

**Issue by borsvadim** [Darkhax-Minecraft/BotanyPots#329]
The hopper pots seems to constantly check and try to push their inventory into the attached storage, to the point that server can become unplayable. It runs fine while there is space in the chest, but goes nuts once everything is full.

Spark Profiler link: https://spark.lucko.me/VlWLEHSpes

![image](https://github.com/Darkhax-Minecraft/BotanyPots/assets/394459/18908bdb-6cea-455d-9e8c-faab06b8e8c4)

At first I though maybe a Redstone toggle could work, but that likely has it's own issues. But maybe a simple On/Off toggle in the GUI for the hopper pot itself?

**Comment by Darkhax** [comment]
Hello, I've done similar tests with vanilla chests and haven't had this issue. I think a more likely explanation here is that the block you are exporting into has some code that could be improved or optimized. If there are any profiles not involving 3rd party mods I can look into that.

**Comment by borsvadim** [comment]
I see. I was using Netherite Chests from Sophisticated Storage under my pots. Guess I should just use vanilla chests for my buffer. Thanks for the reply!

**Comment by codec-d** [comment]
I'm fairly certain this is botany pots attempting to export. tested with mekanism, pipez, storage drawers, integrated dynamics, create, and refined storage. All of them with the exact same lag problems. To be clear, this is actually an interaction between bookshelf and other mods.
