### ISSUE TITLE
QUESTION: RE: Manually harvesting from Botany Pot

### ISSUE THREAD

**Issue by remclave** [Darkhax-Minecraft/BotanyPots#33]
I'm on a server where the modpack author disabled hopper pots. We (the player base) are okay with it since the modpack author desires to minimize what he considers to be too op or too easy for the player. However, when I manually harvest various crops, I get less than 50% drops from the mature crops. The question is: **Is this supposed to happen?**

**Comment by Darkhax** [comment]
Yes this is intended. There are different probabilities and none of the crops have a 100% drop rate by default. Most of them have a 75% chance to drop one of the main item, and then another 5% chance on top to drop 1-2 seeds.

**Comment by remclave** [comment]
Much appreciated. 👍
