### ISSUE TITLE
Request : Recipe Revision[1.20.1:Pam's harvestcraft2-crops,+a(kawaiidishes)] 

### ISSUE THREAD

**Issue by Lufeat** [Darkhax-Minecraft/BotanyPots#332]
I have always used this mod and thank you for your help.

I am using the 1.20.1 compatible version, and some of the crops in the mod [Pam'sHarvestcraft2-crops] are either missing recipes or specify the wrong crop output.
Therefore, may we ask you to correct the following items?

[Problem Areas & Tags]
(Crops and seeds :item:pamhc2crops.item/seeditem , Appearance :block:pamhc2crops.pamcrop)
bokchoy : crop output is agave
sunchoke : no recipe

Also, if it is possible, I would like to ask you to address the following mods for crops.
(MOD:[kawaiidishes])
block.kawaiidishes.coffee_bush (like Sweetberry recipe)

**Comment by Darkhax** [comment]
Hello, thanks for reaching out about these issues. They should now be fixed in [13.0.5](https://legacy.curseforge.com/minecraft/mc-mods/botany-pots/files/4703902). Please let me know if any further changes are required.
