### ISSUE TITLE
Support for "Pizzacraft" Crops

### ISSUE THREAD

**Issue by Maxi90909** [Darkhax-Minecraft/BotanyPots#333]
One can't plant Crops from the Pizzacraft mod inside the BotanyPots. Could you add them as plantable in the pods?

**Comment by Darkhax** [comment]
Thanks for letting me know about this. Support has been added in [13.0.6](https://legacy.curseforge.com/minecraft/mc-mods/botany-pots/files/4706866). Trees are not supported by this mod so the Olive Tree has been added in BotanyTrees [9.0.4](https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/4706861).
