### ISSUE TITLE
Support for "Silent Gear" Crops

### ISSUE THREAD

**Issue by Maxi90909** [Darkhax-Minecraft/BotanyPots#334]
One can't plant Fluffy seeds and flax seeds from the "silent gear" mod inside the pots. Could you add them to the list of being plantable inside the pot?

**Comment by Darkhax** [comment]
Thanks for letting me know about this. Support has been added in [13.0.6](https://legacy.curseforge.com/minecraft/mc-mods/botany-pots/files/4706866).
