### ISSUE TITLE
Support for new Mystical Agriculture seeds

### ISSUE THREAD

**Issue by aAndrew3030** [Darkhax-Minecraft/BotanyPots#335]
Several new seeds were added to Mystical Agriculture, is it possible to add support for these new seeds? Thanks

https://github.com/AllTheMods/ATM-9/issues/214

**Comment by Darkhax** [comment]
Thank you for letting me know. I will try to add support for this soon.

**Comment by Darkhax** [comment]
The [13.0.7](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/4708877) update now includes support for the Mystical Agriculture x EnderIO seeds. Thanks again for letting me know.
