### ISSUE TITLE
Can't till Farmer's Delight rich soil

### ISSUE THREAD

**Issue by devvoid** [Darkhax-Minecraft/BotanyPots#342]
Despite having a pot_interaction in the mod's data, you can't till Farmer's Delight rich soil into rich farmland in a botany pot.

After some experimentation, it looks like this is because it checks for the held item tag "bookshelf:hoes". Changing that to "minecraft:hoes" with a datapack fixes the issue and the soil can be tilled.

Also, looking through the other folders to see if any other files have the same issue, it looks like `till_phytosoil.json` in thermal has the same issue.

Version: 1.20.1 Fabric, Botany Pots 13.0.15.

**Comment by Darkhax** [comment]
Thanks for letting me know about this issue. I've just pushed 13.0.16 which should fix this issue. It will show up on CurseForge and Modrinth soon once it goes through their file processing steps.
