### ISSUE TITLE
Backport 1.12.2

### ISSUE THREAD

**Issue by KEJWII** [Darkhax-Minecraft/BotanyPots#343]
This is a great mod that I would now need to grow pumpkins and melons so that they don't take up much space than 1x1
however, I see that it does not have a version for 1.12.2

I would like a backport
if not, please explain and possibly show alternatives

**Comment by Darkhax** [comment]
Hello, thanks for your interest in the project. Unfortunately the mod relies on features and systems that simply didn't exist in the 1.12.2 version of the game or were significantly different, making them incompatible. The backport would require an extensive rewrite and reworking of core functionality which would be very time consuming and my time is already severely limited. There are plenty of other farming mods you could use to automate farming like the EnderIO Farming Station.
