### ISSUE TITLE
[suggestion] Larger pots

### ISSUE THREAD

**Issue by Rogrom73** [Darkhax-Minecraft/BotanyPots#35]
Hello,

Is it possible to implement larger pot if for example you place a second pot pressing sneak button? Maybe not for Hopper pot but at least for simple one.

**Comment by Darkhax** [comment]
Hello, 

Thanks for the great suggestion. This is something I would like to add eventually. The rendering is the main challenge here as I would like to do this using connected models similar to fences or redstone. Getting the models to render properly will take a significant amount of effort but should work really nicely once it's finished. I can't give an ETA or a promise that this will eventually be added but it is something I will keep in mind.

**Comment by taylorconverse2** [comment]
if not larger pots to combine crops, then for trees maybe?

**Comment by Rogrom73** [comment]
Small trees may be interesting or flower composition :)
I liked to use bonsaï mod but it is causing problem with JEI.

Maybe a good idea to propose multiple pot's height depending of the width
if it is not too much work.

Regards

Le mer. 20 mai 2020 à 18:49, Taylor Converse <notifications@github.com> a
écrit :

**Comment by Darkhax** [comment]
After looking into this more, it is not realistic to add this type of feature while keeping some of the rendering options and optimizations used by the mod. Sorry for anyone who was hoping for this.
