### ISSUE TITLE
Port BotanyHelper.findCrop() Lag fix to MC 1.18.2

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [Darkhax-Minecraft/BotanyPots#351]
@Darkhax, first off, thank you for responding and fixing the findCrop() lag issue so promptly!!!  Second, I am so, SO, sorry, I forgot to mention what version of Minecraft I'm using!  I'm on 1.18.2, and will be for some time, so if it's at all possible, could you down port your fix to that version so that I can make use of it?!?  If not, oh well, at least I helped everyone else out!  Thanks for this great mod!

**Comment by Darkhax** [comment]
Unfortunately I don't have that much time to update older versions, especially with the current pacing of Minecraft updates and the maintaining support for three different mod loaders. I've pushed an update that mirrors the main change made to the 1.20.1 version which should reduce some of the CPU overhead. 

With 1.18.2 hitting 2yrs old in a few days I am planning to end support for this version soon. Of course, the mod is open source and I will still accept pull requests for older versions provided they make sense and are well documented.
