### ISSUE TITLE
Fertilizer handling causes massive lag with certain fake player setup

### ISSUE THREAD

**Issue by chrisliebaer** [Darkhax-Minecraft/BotanyPots#355]
When right clicking with fertilizer in hand, the pot will check if the fertilizer can be applied (or if the crop has already grown). Depending on the outcome of this check, the fertilizer is applied, or the inventory screen is opened. When using modular routers or similar mods for automatically applying fertilizer, this will cause the fake player to open the menu multiple times per second (up to every tick), causing massive performance issues.

I would suggest to never open the inventory while holding fertilizer, regardless of the state of the crop.

**Comment by Darkhax** [comment]
Thanks for letting me know about this, it's very odd that fake players can even open menus. I've pushed a fix to Bookshelf that prevents them from opening up my menus and Spark shows a pretty substantial performance boost with modular routers now. You can get this fix by updating Bookshelf to 20.1.8 on MC 1.20.1, if you use a different version of MC let me know. 

Commit: https://github.com/Darkhax-Minecraft/Bookshelf/commit/a6c3af402350546e4ffc7468b07d903b79c15dd6
