### ISSUE TITLE
Support Pure Berries Mod

### ISSUE THREAD

**Issue by windth001** [Darkhax-Minecraft/BotanyPots#357]
Possible support for this mod: https://modrinth.com/mod/pureberries

**Comment by Darkhax** [comment]
Thanks for the request. Support has been added in version 13.0.20. Unfortunately Modrinth is [down right now](https://status.modrinth.com/) so I can't publish there. The files can be found on CurseForge after they process and approve them. I will push a version for Modrinth once they're back online.

**Comment by purejosh** [comment]
Thanks for adding support!
