### ISSUE TITLE
Change snad:soul_snad to snad:suol_snad - Forge 1.18.2 

### ISSUE THREAD

**Issue by Ex-Kalibur** [Darkhax-Minecraft/BotanyPots#358]
At least for the current version of the Snad mod for 1.18.2 (Snad-1.18.2-1.22.04.15a), Snad works, but not Suol Snad. Checking the config (Common/src/main/resources/data/botanypots/recipes/snad/soil/soul_snad.json) it refers to `snad:soul_snad` instead of `snad:suol_snad`. Changing to the latter via datapack allows it to work.

**Comment by Darkhax** [comment]
Thanks for letting me know about this. There are a few different versions of the Snad mod floating around by different authors and it looks like they're using different item IDs.

**Comment by Darkhax** [comment]
This has now been fixed in [8.1.31](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/5085886). Support for both snad mods has been maintained.
