### ISSUE TITLE
Plastic seed 

### ISSUE THREAD

**Issue by benbenlaw** [Darkhax-Minecraft/BotanyPots#36]
Plastic seed from mystical agriculture do not work in the pots
also found a few other that dont work either

salt seed (Mekanism)
Ender Biotite (Quark)
And some mob seeds

**Comment by Darkhax** [comment]
Mystical Agriculture has an API which allows the available crops to change depending on the mods you have installed. The only crops from that mod supported right now are the default ones and ones that have been contributed by the community. I am going to redirect this issue to #41 and add your entries there.
