### ISSUE TITLE
Crashing with JEI

### ISSUE THREAD

**Issue by DemonSamuraiZero** [Darkhax-Minecraft/BotanyPots#360]
BotanyPot is crashing with the newest JEI update: jei-1.20.4-fabric-17.0.0.30

I got an exit code -1: The game crashed whilst initializing game. 

> Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'jei'!

The crash report says:

> java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'jei'!
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
> 	at net.minecraft.class_310.<init>(class_310.java:487)
> 	at net.minecraft.client.main.Main.main(Main.java:223)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'jei_mod_plugin' provided by 'botanypots'
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
> 	at mezz.jei.fabric.startup.FabricPluginFinder.getInstances(FabricPluginFinder.java:25)
> 	at mezz.jei.fabric.startup.FabricPluginFinder.getModPlugins(FabricPluginFinder.java:16)
> 	at mezz.jei.fabric.startup.ClientLifecycleHandler.<init>(ClientLifecycleHandler.java:37)
> 	at mezz.jei.fabric.JustEnoughItemsClient.onInitializeClient(JustEnoughItemsClient.java:24)
> 	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384)
> 	... 6 more
> Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: net.darkhax.botanypots.addons.jei.JEIPlugin
> 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
> 	... 18 more
> Caused by: java.lang.ClassNotFoundException: net.darkhax.botanypots.addons.jei.JEIPlugin
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
> 	at java.base/java.lang.Class.forName0(Native Method)
> 	at java.base/java.lang.Class.forName(Class.java:467)
> 	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)

**Comment by Darkhax** [comment]
Thanks for letting me know about this, it should now be fixed. The file is currently being processed by CurseForge and Modrinth. Once it's done processing you can find it here https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/5046507
