### ISSUE TITLE
big lag on server

### ISSUE THREAD

**Issue by AndryCola** [Darkhax-Minecraft/BotanyPots#365]
Hi, 
we have noticed that if a pot is full and it can't transfer items in a chest, the minecraft server has a huge lag spike when the game loads that chunk. 
We had tried to break the pot and then the spike lag has gone.
We are playing minecraft 1.20.4 with fabric loader 0.15.6

**Comment by Darkhax** [comment]
Thanks for reporting this issue. How many pots were in the chunk when this error was encountered?

**Comment by AndryCola** [comment]
I had about 25 botany pot all full in 2 chunks near different ( 8 and 17 ) and my fps were from 2 to 6 in that area and sometimes the server crashed. when i broke them the fps were as usually and no more crash or lag.

**Comment by Darkhax** [comment]
I've spent a few hours today trying to recreate this issue but haven't had any luck. I currently have a 10x10 area (100 hopper pots) that are full, and are above chests that are also full. What storage block were you using? Also do you have a copy of the crash log? 

This is what my setup currently looks like. 

![image](https://github.com/Darkhax-Minecraft/BotanyPots/assets/2250798/580a331c-7663-436b-92ad-5660d36dade2)
![image](https://github.com/Darkhax-Minecraft/BotanyPots/assets/2250798/27296240-cbc4-4b29-aaa2-2bbeaa108f72)

**Comment by silentSquid** [comment]
I'd like to add to this, we also encountered absolutely massive lag on our server. (our server is running 1.20.1 Fabric version 0.14.23)

One person had 32 botany hopper pots sitting on top of a line of hoppers feeding into chests.
Basically setup was like this: double chest < hopper < hopper < hopper <hopper < hopper.
Each hopper had a botany hopper pot on top of them. 
We've noticed the lag starting a few days prior, I guess chests were not as full yet and once they were full anyone within something like an 8 chunk radius would come to a complete stand still and fps basically dropped to 0. 
My guess is that somehow sitting on top of a hopper a botany hopper pot was still trying to produce stuff even though everything was full. 
Surprisingly enough botany hopper pots sitting on top of barrels were completely fine.

**Comment by Darkhax** [comment]
@silentSquid Thanks for the additional info. The issue you're describing is extremely bizarre as inventory code is server side meaning there should be no FPS impact especially on a server. I would need to see a spark profile from the client and server to see what's going on there.

**Comment by AndryCola** [comment]
yeas, my situation was similar to silentSquid as setup. 
The fps drops only if the chunk is loaded. 
I can guess that due to the mod is client and server side, when a chunk is full of those stuff on the server, client try to calculate those crops generation and the fps crashes. 
I did a check on the server were it crashed and i found that the server had never crashed, but the client connection was dropped ( i can guess from the client ). 
Unfortunately i haven't the file log with me. 
I could screenshot the old setup so you can replicate it, or you can directly join us to see the situation.

**Comment by silentSquid** [comment]
Yeah actually almost the same as AndryCola. 
Everywhere else on the server was fine and server never crashed. It was strictly client-side fps lag/drop. I dont think clients even ever crashed, just froze there but never disconnected or crashed. And fps would go back to normal if /kill'ed after maybe 20+ seconds
It took our admin maybe over an hour of logging in/out and constant console /kill to manage to snipe hopper pots in creative. After about 6 of them down our admin got like 2 fps back and with more and more of them gone it improved. 
Unfortunately we didnt have spark installed and i dont think our admin wants to deal with that again for repo 😅I was just looking into possible causes and saw this thread.

**Comment by Darkhax** [comment]
@AndryCola Getting as much information about the situation as possible would really help. I've set up my own server to try recreating the issue but still haven't had any luck. If I join the server would you be willing to recreate the exact issue in real time so I can profile things on my client to see where it's going wrong?

**Comment by AndryCola** [comment]
yeah, of course. 
alternately i have just installed sparkle and i could share you the report, but i need some time in order to recreate the spike lag.

**Comment by Darkhax** [comment]
I am closing this issue now due to inactivity. Feel free to open a new issue if there are any new developments.
