### ISSUE TITLE
[SUGGESTION] Add Support for Collector's Reap

### ISSUE THREAD

**Issue by CommanderPhoenix** [Darkhax-Minecraft/BotanyPots#367]
### Minecraft Version

1.19.2

### Mod Loader

Forge

### Feedback

https://www.curseforge.com/minecraft/mc-mods/collectors-reap
Collector's Reap is an addon for Farmer's Delight that adds three new crops. I'm apparently squarebrained and can't make a datapack for the life of me, so baked-in support would be appreciated.

**Comment by Darkhax** [comment]
Thanks for the request, I will look into getting this added soon.

**Comment by Darkhax** [comment]
Sorry this took so long, a new update for 1.19.2 is currently being processed by CurseForge and can be found [here](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/5127292) when it's finished.
