### ISSUE TITLE
[BUG] Bone Mushroom Spores not Yielding Bone Meal

### ISSUE THREAD

**Issue by serioos** [Darkhax-Minecraft/BotanyPots#368]
### Minecraft Version

1.20.1

### Mod Version

13.0.22

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

The Bone Mushroom Spores from Better Nether mod does not give any bone meal. It only drops its spore. It is supposed to drop bone meal too.
![1402-11-21 20_45_27-Greenshot](https://github.com/Darkhax-Minecraft/BotanyPots/assets/93765296/761f2c71-4705-4c59-8308-d74685157a02)

**Comment by Darkhax** [comment]
Thanks for reporting this, a fix has been uploaded to CurseForge and is currently processing. When it's done you can find 13.0.23 for Fabric [here](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/5097408). It now has a 15% chance to drop 1-2 bonemeal which is similar to the secondary drop rate for other crops in this mod like Carrots.
