### ISSUE TITLE
[feature request] new colour: rainbow

### ISSUE THREAD

**Issue by mazunki** [Darkhax-Minecraft/BotanyPots#371]
### Minecraft Version

1.20

### Mod Loader

Forge

### Feedback

Similar to the Fabulous Mana Pool of Botania, I think it would be cute to have botany pots which change colour over time.

I can think of a few different crafting recipes for it, but I'm leaning towards using NBT data for the colour, and use a list to keep adding colours. Combining a botany pot with another will merge the colours and return 2 new pots.

**Comment by Darkhax** [comment]
Hello, thanks for the request. This sounds like an interesting feature but it's definitely out of scope for this mod and would be a very significant change to how pot rendering works. It's not something I plan to add, but the mod code is pretty easy to extend off of so someone could make an add-on if they want.
