### ISSUE TITLE
[SUGGESTION] Compatibility with Ice and Fire

### ISSUE THREAD

**Issue by adozenlionsroaring** [Darkhax-Minecraft/BotanyPots#374]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

It'd be really cool if Botany Pots could work with the Fire Lily, Frost Lily and Lightning Lily from "Fire and Ice" (currently, there is no way to farm these flowers, other than buying the Frost Lily from Scribes). :)

Many thanks for this mod, I've found it extremely useful!

**Comment by Darkhax** [comment]
Thanks for letting me know about this. A new version with Ice and Fire support has been uploaded to CurseForge and is currently being processed. You can find it [here](https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/5167928) when it's approved.
