### ISSUE TITLE
[QUESTION] How to create datapack that adds own recipie?

### ISSUE THREAD

**Issue by DziwnyPanPL** [Darkhax-Minecraft/BotanyPots#376]
### Question

I would like to create that for example: Gunpowder grows on gravel, any example how to do it?

**Comment by Darkhax** [comment]
This is explained in the [wiki](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Datapack-Information). Here's an example for 1.20.4. If you need examples for older versions you can find all of the files for builtin crops here on github, just change the branch to the version you're working with.

```json
{
  "type": "botanypots:crop",
  "seed": {
    "item": "minecraft:gunpowder"
  },
  "categories": [
    "gravel"
  ],
  "growthTicks": 1200,
  "display": {
    "type": "botanypots:aging",
    "block": "minecraft:tnt"
  },
  "drops": [
    {
      "chance": 1.00,
      "output": {
        "item": "minecraft:gunpowder"
      },
      "minRolls": 1,
      "maxRolls": 2
    },
    {
      "chance": 0.15,
      "output": {
        "item": "minecraft:gunpowder"
      },
      "minRolls": 1,
      "maxRolls": 2
    }
  ]
}
```
