### ISSUE TITLE
[BUG] Lag on Dedicated Server

### ISSUE THREAD

**Issue by Aikoyori** [Darkhax-Minecraft/BotanyPots#377]
### Minecraft Version

1.20.1

### Mod Version

13.0.24

### Mod Loader

Fabric

### What environment are you running the mod in?

All

### Issue Description

Seems to be related to #365 

Some small investigation by me

![image](https://github.com/Darkhax-Minecraft/BotanyPots/assets/12034280/b3adc937-57c3-4607-ae77-15a2b593f470)

Notable Addons used 
https://github.com/mango-buff/BotanyPotsOrePlanting

**Comment by Darkhax** [comment]
Hello, thanks for including a spark profile. This issue is related to how inventories are handled on Fabric and has already been reported [here](https://github.com/Darkhax-Minecraft/BotanyPots/issues/322). Several performance fixes are being worked on for this.
