### ISSUE TITLE
[FEEDBACK] <Config Optins>

### ISSUE THREAD

**Issue by WayanD157** [Darkhax-Minecraft/BotanyPots#378]
### Minecraft Version

1.18.2

### Mod Loader

Forge

### Feedback

Just like in Mod version 1.16.5, which had the mod configuration file with these options:

#Client side configurations for the mod. Modpacks should not ship non-default versions of this file!
[client]
#Whether or not crops should yield in pots.
renderCrop = true
#Whether or not break effects should occur when harvested.
breakEffects = false
#The yield distance of a botany pot.
#Range: 1.0 ~ 4096.0
renderDistance = 16.0
#Whether or not the growth animation should be played.
useGrowthAnimation = false
#Whether or not the soil in pots should be rendered.
renderSoil = true

I would like to have these same options in the 1.18.2 version.

My PC doesn't have the best configuration to support many mods, it's very basic, and these options in version 1.16.5 saved me a lot of FPS and RAM (even if it doesn't seem like it, but it helped a lot). And knowing that version 1.18.2 doesn't come with these settings made me rethink whether or not to use the mod.

I leave my FeedBack to you here!

**Comment by Darkhax** [comment]
I've explained this a few times now, but the "performance" options did not improve FPS or lower RAM usage. They were only added to prove this point, and after extensive benchmarking the point was proven. The stock rendering performance of a botany pot already outperforms a vanilla sign and I will continue to improve the code where it makes sense, but this is unreasonable and would hold botany pots to a higher standard than any other mod or vanilla feature. If you're having performance issues with the pots, it's usually related to the item-transfer/storage mods that you're using.
