### ISSUE TITLE
[CRASH] Game crashes on new world creation screen

### ISSUE THREAD

**Issue by dizzydizzee** [Darkhax-Minecraft/BotanyPots#379]
### Minecraft Version

1.19.2

### Mod Version

9.0.38

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

As soon as I go to create a new world, the game says 'preparing for world creation' then 'saving world' and crashes. Tested with other mods on the instance, it is definitely botany pots that is causing this

### Crash Log

[https://paste.ee/p/A9d3n](https://paste.ee/p/A9d3n)

**Comment by Darkhax** [comment]
Hello, nothing about your crash log indicates this is a botany pots issue. Some mod has registered a recipe with a null type which we do not do. It's possible they only register the recipe if our mod is installed, but that would be for them to fix. I would advise continuing to disable mods while botany pots is enabled until it starts working again.

**Comment by dizzydizzee** [comment]
Thank you for the quick response! I do not have much technical knowledge of what you described, but will do as you suggested! Sorry for the bother!
