### ISSUE TITLE
crash : Rendering Block Entity

### ISSUE THREAD

**Issue by lebanni** [Darkhax-Minecraft/BotanyPots#38]
forge-1.15.2-31.2.0.jar
BotanyPots-1.15.2-2.0.19.jar
Bookshelf-1.15.2-5.6.37.jar

Minecraft client crashed to desktop.

[crash-2020-05-19_20.37.49-client.txt](https://github.com/Darkhax-Minecraft/BotanyPots/files/4652484/crash-2020-05-19_20.37.49-client.txt)

[latest.log](https://github.com/Darkhax-Minecraft/BotanyPots/files/4652487/latest.log)

**Comment by Darkhax** [comment]
Thanks, this should now be fixed.
