### ISSUE TITLE
[FEEDBACK] Convert farmland to dirt when removing

### ISSUE THREAD

**Issue by nojomyth-dev** [Darkhax-Minecraft/BotanyPots#380]
### Minecraft Version

1.20.4

### Mod Loader

Fabric

### Feedback

Currently, if you till a dirt block with a hoe inside the pot, it creates farmland by default. However, a player can just take out the farmland and have an "illegal" item. This is a minor issue, however, it would be cool to have a "remove" interaction that can be configured like the other ones. (Or, if it already exists and i overlooked it, it is added to the defaults for farmland)

**Comment by Darkhax** [comment]
Hello, this was actually somewhat of an intended feature. It's not that uncommon for mods to add a crafting recipe for farmland and I thought this would be an interesting way to let players get it. It may be possible to add a replacement hook to turn it back into dirt but Minecraft's inventory code would really complicate that. Catching items that have been shift clicked out of the inventory would be especially tricky. 

If it really bothers you I would recommend finding an "illegal item catcher" mod that can convert it back when it's in the players inventory. You could also use something like CraftTweaker to do that, or just remove the tilling soil recipe from my mod.

**Comment by nojomyth-dev** [comment]
Ah, okay, then it's fine

Doesn't bother me, just wasn't sure if this was intended or not. Thank you!
