### ISSUE TITLE
Suggestion: Cold Sweat compat

### ISSUE THREAD

**Issue by AnasterianSunstrider** [Darkhax-Minecraft/BotanyPots#383]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

The mod only has 1 plant and it would be nice to be able to grow it in a pot for a reliable supply

**Comment by Darkhax** [comment]
Thanks for the feature request. Sorry it took so long to get around to this one. A new version with support is currently being processed by CurseForge.
