### ISSUE TITLE
[FEEDBACK] Some Regions Unexplored recipes are missing bookshelf load condition checks

### ISSUE THREAD

**Issue by DragonS0u1623** [Darkhax-Minecraft/BotanyPots#388]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

As mentioned in the title, in the latest update for 1.20.1 that added compatibility for regions unexplored, some of the recipes are missing bookshelf checks which mean that they get loaded regardless of whether the mod is installed or not. I have gone through and made a list of the recipes missing these checks, and am also willing to help with adding the checks to these files if that doesn't disrupt your workflow.

The affected recipes:

- windswept_grass
- white_trillium
- waratah
- tsubaki
- stone_bud
- steppe_tall_grass
- steppe_grass
- salmon_poppy_bush
- sandy_tall_grass
- sandy_grass
- prismoss_sprout
- poppy_bush
- mycotoxic_grass
- medium_grass
- mallow
- hyssop
- hibiscus
- glistering_sprout
- glistering_fern
- glistering_bloom
- frozen_grass
- felicia_daisy
- elephant_ear
- dusktrap
- duskmelon
- dropleaf
- dorcel
- daisy
- corpse_flower
- cobalt_roots
- clover

**Comment by Darkhax** [comment]
Thank you for reporting this issue. It should now be fixed thanks to your PR.
