### ISSUE TITLE
[FEEDBACK] Can you add Glowshrooms (from Quark mod) to botany hopper?

### ISSUE THREAD

**Issue by eavsabban** [Darkhax-Minecraft/BotanyPots#392]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

Can you add Glowshrooms (from Quark mod) to botany hopper? It's so rare to find this mushroom ;o Thank you

**Comment by Darkhax** [comment]
Thank you for the feature request, sorry that it took so long to get to this. This has now been added and a new update is being processed on CurseForge.
