### ISSUE TITLE
[BUG] Crafttweaker import function not finding ZenCrop and ZenSoil

### ISSUE THREAD

**Issue by KaranMaia** [Darkhax-Minecraft/BotanyPots#395]
### Minecraft Version

1.20.1

### Mod Version

13.0.29

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

I'm trying to edit the botany recipes with crafttweaker like the guide posted on this github (https://github.com/Darkhax-Minecraft/BotanyPots/wiki/CraftTweaker-Support) but when I use that import function it says type not found, do I need to do something prior to that?

My script: https://pastebin.com/if22FAJL
the error: 
![image](https://github.com/Darkhax-Minecraft/BotanyPots/assets/73917457/19806cff-e472-47ad-aa68-a4a1ffbf71e7)

**Comment by Darkhax** [comment]
Hello, unfortunately CraftTweaker support is not available on 1.20.1. The only way to add/modify crops is through data packs. CraftTweaker support will be re-added for 1.20.1 at some point but I do not have a time frame for this.
