### ISSUE TITLE
[FEEDBACK] CONFIG FILE MISSING

### ISSUE THREAD

**Issue by DanjonNoRyu** [Darkhax-Minecraft/BotanyPots#396]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

Hello, it would be very pleasant to have a config file. Many users have problem for a low-end pc so having a config file like the past versions would be very usefull and we know that you are not "leaving" us, since there is the bug with the craft tweeker so people like me can't change configs and can't add "new" crops with the config we would. Thanks in advange I'll look after it.

**Comment by Darkhax** [comment]
Hello,

There is currently no reason for this mod to have a configuration file. When there is, I will add one. 

CraftTweaker support is not broken, I just haven't had the time to add support on newer versions. You can still use the data pack system to add/remove/modify crops and soils. This can even be done with CraftTweaker using their data APIs. Using a configuration file for complex data like this is not appropriate. 

The performance options on 1.16.5 did not have any meaningful effect on FPS, even on older hardware. These options were aggressively demanded by uninformed players and I reluctantly added them so they could see this for themselves. Extensive benchmarking proved that these options were useless. Botany pots are already far more optimized than most mods and the FPS impact is less than a vanilla sign. FPS issues are usually related to the pipe/storage mod that you are using. When real performance issues or optimizations are found they will be addressed.
