### ISSUE TITLE
Compatibility Request: Buzzier Bees

### ISSUE THREAD

**Issue by ALoveOverall** [Darkhax-Minecraft/BotanyPots#40]
Buzzier Bees adds quite a few new and unique flowers that would look beautiful potted. Not to mention some of these flowers can be directly crafted into some of the more uncommon dyes. 

https://www.curseforge.com/minecraft/mc-mods/buzzier-bees

**Comment by Darkhax** [comment]
![image](https://user-images.githubusercontent.com/2250798/85511206-e60e6f80-b5e7-11ea-8fa8-45d20be41d13.png)
