### ISSUE TITLE
[Feature Request] Add Support for Thermal Expansion Rubber Trees

### ISSUE THREAD

**Issue by BonaireDreams** [Darkhax-Minecraft/BotanyPots#400]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

Thermal Expansion Rubber trees currently do not work in Botany pots. Would be awesome if they were added.

**Comment by Darkhax** [comment]
Thermal Rubberwood is [already supported](https://github.com/Darkhax-Minecraft/BotanyTrees/blob/1.20.1/common/src/main/resources/data/botanytrees/recipes/thermal/rubberwood.json). Make sure you have the latest version of the Botany Trees add-on installed. If you're playing a mod pack it's also possible that the author of that pack has disabled the recipe.
