### ISSUE TITLE
[FEEDBACK] Add support for Vintage Delight

### ISSUE THREAD

**Issue by CommanderPhoenix** [Darkhax-Minecraft/BotanyPots#401]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

https://www.curseforge.com/minecraft/mc-mods/vintage-delight
Support for Vintage Delight would be incredibly helpful, since I'm not knowledgeable enough to make a datapack.

**Comment by Darkhax** [comment]
Thank you for the request. Support for Vintage Delight has been added in Botany Pots 13.0.38.
