### ISSUE TITLE
[QUESTION] Datapack Issue 1.20.1

### ISSUE THREAD

**Issue by AdrinMin** [Darkhax-Minecraft/BotanyPots#408]
### Question

Hello I'm not sure on how to get a datapack running for 1.20.1 for a modded crop that is added using mystical customization. Some help would be greatly appreciated. 
[testpack (2).zip](https://github.com/user-attachments/files/16319963/testpack.2.zip)

**Comment by Darkhax** [comment]
Hello, your TNT crop from `test.json` works perfectly fine. Mystical Customization should be handled the same way, just copy the block and item IDs that appear in game. Your `soul_dust.json.json` file looks fine as well, but I would recommend removing the second `.json` from the file name. I can't say if your IDs are correct though, as those are from your personal configurations. You can see them in game using the f3 screen and advanced item tooltips (f3 + h).

**Comment by AdrinMin** [comment]
Thank you so much for the tips also I managed to get it working! Once again thanks for the help and the amazing mod!

**Comment by Darkhax** [comment]
Awesome, I am glad you were able to make it work.
