### ISSUE TITLE
[BUG] Water/Lava fluid textures are not correct on pot

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/BotanyPots#409]
### Minecraft Version

1.20.4

### Mod Version

16.0.4

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

When I add a water/lava bucket  as soil the textures are the textures of different items instead of the fluid texture.

I made a new minecraft client with only this mod installled. No shaders and no other mods installed.
Modrinth installs automaticly these mods to have your plugin working:
1. Fabric API
2. Bookshelf

I added the waterbucket and this is the resulting texture:

![image](https://github.com/user-attachments/assets/4bf8c426-b154-447b-8427-86a3adc2eabb)

*NOTE* : The mod it working and retreives kelp

**Comment by Darkhax** [comment]
Thank you for reporting this issue, I've confirmed it on Forge as well. This is an issue in the Bookshelf dependency, I should have a fix for it soon.

**Comment by ghost** [comment]
You are welcome :), Thanks for your response.

**Comment by Darkhax** [comment]
This issue should be fixed in Bookshelf 23.1.9. The file is being processed on CurseForge and Modrinth and should be available publicly soon.

Fixed by https://github.com/Darkhax-Minecraft/Bookshelf/commit/bfecc97057117e5ebecba94f6f9ed062414df36c
