### ISSUE TITLE
Additional Mystical Agriculture Seeds

### ISSUE THREAD

**Issue by Omni35** [Darkhax-Minecraft/BotanyPots#41]
I've noticed 6 seeds from Mystical Agriculture aren't useable in Botany Pots.
Wondering if that's intended.

Seeds currently not working in the pots from MA: 
Honey Seed (Vanilla)
Ender Biotite Seed (Quark)
Mystical Flower Seed (Botania)
Manasteel Seed (Botania)
Elementium Seed (Botania)
Terrasteel Seed (Botania)

**Comment by Darkhax** [comment]
Hello, 

No this is not intended. Mystical Agriculture registers new seeds depending on which mods the player has available and other plugins. Any crops beyond the vanilla ones in mystical agriculture have been contributed by community members.

**Comment by Omni35** [comment]
Oh, I see, thanks for the explanation.
I'll leave this open in case someone wants to do that then.

**Comment by Darkhax** [comment]
> benbenlaw commented on May 14 •
> 
>Plastic seed from mystical agriculture do not work in the pots
also found a few other that dont work either
>
> salt seed (Mekanism)
> Ender Biotite (Quark)
> And some mob seeds
