### ISSUE TITLE
[BUG] Better Nether and Botany Pots recipe error message on log

### ISSUE THREAD

**Issue by ghost** [Darkhax-Minecraft/BotanyPots#410]
### Minecraft Version

1.20.4

### Mod Version

16.0.4

### Mod Loader

Fabric

### What environment are you running the mod in?

Client

### Issue Description

Hi again :),

Thanks for your fix with the fluid texture.

I created an empty instance again in modrinth with Better Nether together with botany pots.

![image](https://github.com/user-attachments/assets/c161aaaf-d33d-4a96-85a4-ebfd7fec1e50)

Now I am presented with this error:

![image](https://github.com/user-attachments/assets/d4058bac-dd3d-4507-b828-3938dc5c394e)

This time I am not sure if it is intended to work like this but I can not grow jellyfish_mushroom_saplings in botany pots even when I use the proper soil.

![image](https://github.com/user-attachments/assets/fbb4649c-f63d-4e76-8544-136871e00b68)

![image](https://github.com/user-attachments/assets/c53ba3a7-24e9-42f3-b652-d34895ba5f52)

**Comment by Darkhax** [comment]
Thanks for reporting this issue. It should be fixed in the new 16.1.5 update.

**Comment by ghost** [comment]
Thank you very much:)
