### ISSUE TITLE
[FEEDBACK] Mod Integration for BloomingNature by satisfy

### ISSUE THREAD

**Issue by lunakibby** [Darkhax-Minecraft/BotanyPots#412]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

Would like to suggest integration with the 9 saplings added by BloomingNature, I absolutely love the texturing of the Chestnut wood and would like to use it with botany pots!

https://www.curseforge.com/minecraft/mc-mods/lets-do-bloomingnature

**Comment by Darkhax** [comment]
Thank you for the feature request. Trees and saplings are handled by the Botany Trees add-on. Support for Blooming Nature has been added in 9.0.14. 

https://github.com/Darkhax-Minecraft/BotanyTrees/commit/9bfa518
