### ISSUE TITLE
[QUESTION] I can't get Craft Tweaker to recognize Botany Pots

### ISSUE THREAD

**Issue by DeadBreadHero** [Darkhax-Minecraft/BotanyPots#416]
### Question

Here is my code below.
________________________________________________________________________________________________

> import crafttweaker.api.item.IItemStack;
> import crafttweaker.api.item.ForgeItemStack;
> import crafttweaker.api.recipe.type.Recipe;
> import crafttweaker.api.recipe.MirrorAxis;
> import crafttweaker.api.mod.Mod;
> import crafttweaker.api.mod.Mods;
> import mods.botanypots.ZenSoil;
> import mods.botanypots.ZenCrop;
> import mods.botanypots.ZenFertilizer;
> 
> val soils = <recipetype:botanypots:soil>;
> val crops = <recipetype:botanypots:crop>;
> val fertilizers = <recipetype:botanypots:fertilizer>;
> 
> // soils.create(id, input, renderBlock, growthModifier, category);
> 
> val ImmWeatheringMulch = soils.create("mulch_block", <item:immersive_weathering:mulch_block>, <blockstate:immersive_weathering:mulch_block>, 0.25, [ "mulch" , "dirt" ] );
________________________________________________________________________________________________

And I keep getting this error message when I reload: 

________________________________________________________________________________________________

> [ERROR]: Error while compiling scripts:  _File_Name.zs_ Could not find type mods.botanypots.ZenCrop
________________________________________________________________________________________________

and then similar errors for "ZenCrop" and "ZenFertilizer". I have no clue what I am doing wrong. I copied my code directly from the wiki and then replaced the names of things. I spent forever pouring over it to see where I went wrong, but, frankly, I have virtually no experience with coding. It is all Greek to me.  Please help.

**Comment by RaparigaDoSul** [comment]
I have the same problem. Did you find a solution?

**Comment by Darkhax** [comment]
Unfortunately BotanyPots has not had CraftTweaker support since 1.16.5. It's being worked on but the constant update cycle hasn't left us with much time to work on these features. You can use data packs or CraftTweakers built-in data recipe system for now.
