### ISSUE TITLE
[Bug // 1.18.2 - 8.1.32] High Tick Usage from Pots

### ISSUE THREAD

**Issue by FocalFlare** [Darkhax-Minecraft/BotanyPots#418]
### Question

# Initial Observation
_I feel like I may ask something stupid, so let me ask it at the end and leave you with this:_

_While using the botany pots in one of my worlds, I noticed that, via Observable, they were taking up a lot of ticks in the world over everything else. So I went into one of my test worlds to do some testing with both the hopper and the regular pots--which I labeled as red and yellow--and proceeded to profile their tick usage with observable. I noticed that the hopper pots use a small amount of ticks when idling, and a **crap** ton of ticks (exaggeration, I know) when they either have anything in their inventories or are doing something._

## Testing
_The following tests were done using the profiling mod **Observable**. The most recent profile I saved in the screenshot for the pots being active focuses on only these two pots, but the full profile for the entire world is here:_ 
[2024-08-18--01.20.09.json](https://github.com/user-attachments/files/16647494/2024-08-18--01.20.09.json)
### Active Growth
_Here's the tick usage (in us/t) on the pots not doing anything (again, yellow = hopper and red = regular). This is the "reference profile"._
![2024-08-18_01 15 16](https://github.com/user-attachments/assets/38dc1f2a-2715-4046-8830-65f74192c8a1)

And the tick usage on them while they grow crops.
![2024-08-18_01 16 25](https://github.com/user-attachments/assets/490e3fe7-e505-484d-a4e8-f3736b47bff8)
### No Crops in Pots
Here's what the tick usage of the pots is like when there are only crops in each pot.
![image](https://github.com/user-attachments/assets/248baa5a-8327-4828-9b65-50567c0fb76f)
### No Soil in Pots
Same deal, but this time there's no required soil in each pot.
![image](https://github.com/user-attachments/assets/83089a2d-b30a-4706-b5b0-c5982567112b)

## Question
_Again, probably a stupid question because I feel like I'm missing something here, but is this intended or is this something to be looked into? I know I should've opened this as a bug issue, but I'm not too sure whether it's either a bug or it's actually meant for the hopper pot to cause high tick usages like this._

# Game Info (related to this issue only)
* Minecraft version: 1.18.2
* Forge version: 40.2.21
* Mod version: 8.1.32
* Observable version: 2.2.3

**Comment by FocalFlare** [comment]
_Not sure if @Darkhax is already aware of this or not, but I changed "Question" in the title to "Bug" since—after enough time of inactivity on this issue within the last 3 weeks of it being open—I've came to the conclusion that this seems to be something that's not supposed to be intended more than something that is to be intended._

**Comment by FocalFlare** [comment]
_@Darkhax This issue will be made again at some point, but feel free to reopen this issue if you have any ideas on this one. I will shelf this issue will for now due to there being no response._

**Comment by Darkhax** [comment]
Hey, sorry for not replying sooner. I haven't been very active the last few weeks because I have been dealing with some personal stuff. The results you have shared are very interesting and I would be open to looking into them. A few issues related to inventory updates have been found and that is likely partly responsible for the lag you're seeing. https://github.com/Darkhax-Minecraft/BotanyPots/issues/421

**Comment by FocalFlare** [comment]
_Just looked at some of the info in #421 (made 3 issues after this one). Sadly I don't think I know what else other than serving as a backbone for select mods that Bookshelf does, so I wouldn't really know of the things that it's doing. Surprisingly the OP of #421 discovered that as the cause._

_They also seemed to have brought up an add-on **Botany Pots Tiers** which I've been using myself, but I've never had issues with that alone if any, oddly enough. I also noticed that they made an add-on that fixes said issue, but at the moment it's for Fabric 1.20.1 (it's in beta so I can't really expect a lot lol)._

**Comment by FocalFlare** [comment]
_I just wanted to add to this. I curiously went to see something in a different world (away from the same test world I was in when I took those screenshots), and..._
![Image](https://github.com/user-attachments/assets/916421cc-fdfd-43c9-b16e-811867c1345f)
![Image](https://github.com/user-attachments/assets/17e93855-ec5d-4939-a6c7-44d47a577fb3)
_...the weird thing about this issue that #421 mentioned is that—and I've only tested this with one tier but noticed it from the tier after it—the elite pots (and I'm assuming other pots) don't use hundreds of ticks per second like the normal pots do._
