### ISSUE TITLE
Add ability for items to change/mutate crops on right click. (like hoe)

### ISSUE THREAD

**Issue by Hubry** [Darkhax-Minecraft/BotanyPots#42]
Found while using the modpack of Vazkii's patreon server ([link](https://www.curseforge.com/minecraft/modpacks/vazkii-patreon)), Forge 31.1.87, Botany Pots 2.0.14, Botania r1.15-384.

Reproduction: Try to place dirt or grass into the pot, then use the overgrowth seed (for enchanted soil) or a hoe (for farmland) on the pot. Nothing changes. Then use the the item on a placed block and try to silk touch the block, only to realize it drops dirt even with silk touch.

While both of those block's items can be still accessed with things like forcing the block to turn into a falling block entity (eg. using Psi's Collapse Block trick), not every modpack will have access to those methods, and it's expected that both would be accessible by default.

**Comment by Darkhax** [comment]
Hello, thanks for reporting. Not all soils are meant to be obtainable under normal play although support still exists for when those soils become obtainable. The ability to upgrade soils using items will come in a future update.

**Comment by Darkhax** [comment]
This feature was finally added in 1.18.2. Examples [here](https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.18.2/Common/src/main/resources/data/botanypots/recipes/minecraft/pot_interaction/till_farmland.json)
