### ISSUE TITLE
[FEEDBACK] Trees

### ISSUE THREAD

**Issue by kienerxyzzy** [Darkhax-Minecraft/BotanyPots#428]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

We have bamboo and nether woods plantable in the pot.
So please do all of the wood types.

**Comment by Darkhax** [comment]
Bamboo and mushrooms are not trees, even if they have a building block associated with them. Use this addon. https://www.curseforge.com/minecraft/mc-mods/botany-trees
