### ISSUE TITLE
[QUESTION] datapack help 1.20.1

### ISSUE THREAD

**Issue by Gravitrax39** [Darkhax-Minecraft/BotanyPots#429]
### Question

I'm attempting to make this mod work with the lets do vinery and brewery mods but the seeds refuse to even go into the pot. Some help would be really appreciated.
[alcoholpots.zip](https://github.com/user-attachments/files/16920656/alcoholpots.zip)

**Comment by paula867** [comment]
Hey, were you successful adding the crops you wanted? I'm currently wanting to do the same with some trees from Nature's Spirits but can't seem to figure it out.

**Comment by Gravitrax39** [comment]
I did figure it out. the problem was the display. I was trying to reference a block that didn't exist because I assumed it did. so I'd suggest to double check all of the names to make sure they're real.
