### ISSUE TITLE
Typo on the wiki

### ISSUE THREAD

**Issue by G-Stav** [Darkhax-Minecraft/BotanyPots#43]
"Getting All Ids
This will give you an array of all the known crop ids at the time.

Fertilizer.getAllIds();

Removing All Crops
This will completely remove all the crops currently registered. This is useful for if you want to recreate all the data from scratch through scripts.

Fertilizer.removeAll();"

Not sure but I'm thinking it should be:
Crop.getAllIds(); and Crop.removeAll();

On a side note, where is it that it prints these arrays? Trying to add two soils, but I'm having trouble finding the categories which are implemented instead of having to create my own categories.

**Comment by Darkhax** [comment]
Thanks for spotting this. The IDs are not printed, it just gives you access to all of them in ZenScript as a variable.
