### ISSUE TITLE
[CRASH] 1.19 JEI crash When Pressing U

### ISSUE THREAD

**Issue by Enterprise12nx01** [Darkhax-Minecraft/BotanyPots#432]
### Minecraft Version

1.19.2

### Mod Version

9.0.44

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

Pressing U on anything like iron ore, and navigating past the botany pots tab on the top of jei causes an instant crash
jei version 11.6.0.1019 release version.

### Crash Log

https://pastebin.com/gifL19dX

**Comment by Darkhax** [comment]
Hello, the crash log shows that this is a JEI issue. Try updating JEI to `11.8.0.1030` and try again. If the issue continues to happen, report this to JEI.

**Comment by Enterprise12nx01** [comment]
> Hello, the crash log shows that this is a JEI issue. Try updating JEI to `11.8.0.1030` and try again. If the issue continues to happen, report this to JEI.

updated to new jei version fixed it, although thats beta. i feel that it should support the current "stable release" version of JEI

**Comment by Darkhax** [comment]
@Enterprise12nx01 The bug is entirely in the JEI code so I can't magically make the stable release work for you.
