### ISSUE TITLE
[FEEDBACK] Mystical Agriculture Inferium is not supposed to produce fertilized essence

### ISSUE THREAD

**Issue by diefesson** [Darkhax-Minecraft/BotanyPots#439]
### Minecraft Version

1.20.1

### Mod Loader

Forge

### Feedback

All Mystical Agriculture crops have a chance of producing Fertilized Essence with exception of inferium crops.
Still inferium crops planted on Botany Pots are producing it.
![Captura de tela 2024-11-06 152250](https://github.com/user-attachments/assets/bafc235c-f5b7-4b98-b3b3-666b7da6505b)

**Comment by diefesson** [comment]
Opened a few pull requests
#440
#441 
#442
#443

**Comment by Darkhax** [comment]
Thanks for looking into this. Your PRs have been merged and new builds will be published to CurseForge and Modrinth soon.
