### ISSUE TITLE
 Compatibility Request: work in 1.12

### ISSUE THREAD

**Issue by landerson78** [Darkhax-Minecraft/BotanyPots#44]
Would be nice if you could make a 1.12 version since more mod packs for 1.12 than most other minecraft versions besides maybe 1.7. Would love to see that work in 1.12 awesome mod ty for all the hard work you have put into it.

**Comment by Darkhax** [comment]
Hello, 

This mod depends heavily on data pack features which are not available on 1.12.x so it is not realistic to backport to that version. Also the majority of players have already left 1.12 for newer versions.
