### ISSUE TITLE
[CRASH] <title>

### ISSUE THREAD

**Issue by DxDMorgan** [Darkhax-Minecraft/BotanyPots#447]
### Minecraft Version

1.20

### Mod Version

V7

### Mod Loader

Forge

### What environment are you running the mod in?

Dedicated Server

### Issue Description

The game server crashes randomly. After a quick analysis, this would come from an interaction of a mob with the claims of the mod "Xaero's World MAp"

### Crash Log

[crash-2024-11-14_21.02.01-fml.txt](https://github.com/user-attachments/files/17893566/crash-2024-11-14_21.02.01-fml.txt)

### Are you doing anything weird?

Just play casually, crashes are completely random.

**Comment by Darkhax** [comment]
What makes you think this crash is related to Botany Pots? Based on the log file you provided, you don't even have my mod installed.
