### ISSUE TITLE
[Compatability Request] Compatibility with mystical agriculture/agradditions to not allow crops that require cruxes

### ISSUE THREAD

**Issue by tobi-polar** [Darkhax-Minecraft/BotanyPots#46]
Some seeds by default require a block known as a crux to be placed under the farmland in order to grow. Planting them in the botany pot circumvents this requirement. 

it'd be good to have an option to enable/disable plants with cruxes from being able to grow in the botany pots.

**Comment by Darkhax** [comment]
Modpack authors can already remove crops using CraftTweaker. This mod has no access to the crop data within mystical agriculture so it can not auto disable all of these crops for you.
