### ISSUE TITLE
[Enhancement] Immersive Engineering support

### ISSUE THREAD

**Issue by JakeMoe** [Darkhax-Minecraft/BotanyPots#49]
## Request
Went to try and grow some Industrial Hemp in a pot, only to find it wouldn't go in.  I saw I can add support via CraftTweaker, which I'll have a look at, but figured I'd see if official support for Immersive Engineering could be added.

## Versions in use
Minecraft: 1.15.2
Forge: 31.2.29
Botany Pots: 1.15.2-2.0.24
Immersive Engineering: 0.15-99

**Comment by Darkhax** [comment]
Thanks, this has been added.
![Untitled](https://user-images.githubusercontent.com/2250798/87108734-7f798a80-c252-11ea-8987-0de15056364c.png)

**Comment by JakeMoe** [comment]
You legend, cheers :-) I have a feeling your growth rates are probably going to nerf what I put in CraftTweaker; I kept meaning to tweak it for balance...

**Comment by Darkhax** [comment]
The base rate is 2400 (120 seconds). Might be a bit too nerfed, I am not sure how rare it's meant to be in that mod lol.

**Comment by JakeMoe** [comment]
FWIW, I know that hemp normally requires sunlight (not just bright light) to grow, it needs to grow two high to harvest, but harvesting only takes the top block off, so the next one comes much faster.  Also, the drop rate per harvest (according to JEI) is 4-6 hemp and 1-2 seeds.  I also know that for the windmill sails, you need something like 8 stacks of hemp, so it needs a lot, and takes a while for me to get the amount I need.  However, hemp is an alternate source of string and wool, so not sure how fast you'd want to make it grow.

Having said that, I had put 4-6 hemp and 1-2 seeds at 100% every 1000 ticks (the tick count seemed to match other plants I looked at the recipe for), and that felt a bit fast.  Possibly could have dropped to 50% - 75% output.
