### ISSUE TITLE
Iron ingots named "clay" can be used as cheaty dirt.

### ISSUE THREAD

**Issue by Vaelzan** [Darkhax-Minecraft/BotanyPots#53]
https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.15.2/src/main/resources/data/botanypots/recipes/soil/iron.json

(leave a test soil in by mistake? :P)

**Comment by Darkhax** [comment]
oof, thanks for reporting.

**Comment by Darkhax** [comment]
Fixed in https://github.com/Darkhax-Minecraft/BotanyPots/commit/11b47a69ddc88722ea78a5285c1d0568eee7b86d. Will be on CF soon.
