### ISSUE TITLE
Crash on custom 1.16 forge modpack

### ISSUE THREAD

**Issue by NxD136** [Darkhax-Minecraft/BotanyPots#58]
I don't know if this mod is causing the issue or not. But when I remove it from the mods folder I don't get the error anymore. I'm not the best at reading crash reports so I hope that you can help me figure this out because I love your mod and I want it in my modpack!

**Crash report :**
[crash-2020-07-19_03.35.58-client.txt](https://github.com/Darkhax-Minecraft/BotanyPots/files/4943393/crash-2020-07-19_03.35.58-client.txt)

**Comment by Darkhax** [comment]
Not sure what my mods would have to do with this. It's `java.lang.NullPointerException: Registry Object not present: modularrouters:item_router` so modular routers.
