### ISSUE TITLE
Mystical Agriculture Inferium Seed on upgraded Essence Farmland

### ISSUE THREAD

**Issue by JakeMoe** [Darkhax-Minecraft/BotanyPots#59]
I've just upgraded my base Inferium Farmland to Tertium Farmland, which JEI tells me should give me a boost to essence growth in pots, but I'm not sure I'm seeing that increase.  Does Botany Pots respect the farmland modifiers, or does it treat them all equally?  i.e., is JEI showing me the data for the farmland block in general, or does it show the right info for upgraded farmland in a Botany Pot?

FWIW, I'm using BotanyPots 1.15.2-2.0.27

**Comment by Darkhax** [comment]
Tertium has a growth modifier of 0.3 vs inferium which is 0.2 so roughly a 10% difference. When growing Air Seeds for example it will be 48 seconds vs 42 seconds.
