### ISSUE TITLE
Add support for oh the biomes

### ISSUE THREAD

**Issue by jlatham82** [Darkhax-Minecraft/BotanyPots#60]
Can you add support for Oh the Biomes You'll go?

**Comment by rowanthemodder** [comment]
This should be everything needed for Oh the Biomes You'll Go
[botanypotbyg.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5351785/botanypotbyg.zip)

**Comment by rowanthemodder** [comment]
> 
> 
> This should be everything needed for Oh the Biomes You'll Go
> [botanypotbyg.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5351785/botanypotbyg.zip)

Oops, I accidentally added my template for the flowers inside the file, removing the file "flower_template.json" should be all that's needed

**Comment by Darkhax** [comment]
Thanks, added in https://github.com/Darkhax-Minecraft/BotanyPots/commit/c316cb69512e2dd630a50edb9805c9c1adc61999
