### ISSUE TITLE
Help with Botany Pots "no such symbol" for 1.16.1

### ISSUE THREAD

**Issue by papaworld** [Darkhax-Minecraft/BotanyPots#61]
Thank you for a superior mod.
Copied your example scripts because I'm having errors with my scripts... getting the same errors, if you could help me please.

import mods.botanypots.Crop;
Crop.create("examplepack:gold_1", <item:minecraft:gold_nugget>, <blockstate:minecraft:gold_block>, 3000, ["dirt"]);
Crop.addDrop("examplepack:gold_2", <item:minecraft:gold_block>, 1.0, 1, 1);

ERROR: Could not find type mods.botanypots.Crop
c05 Botany Pots.zs:5:0 No such symbol.Crop
c05 Botany Pots.zs:6:0 No such symbol.Crop

MC 1.16.1
FML: 32.0.71
CraftTweaker: 7.0.0.12
Botany Pots: 3.0.4

My failed Recipie:

import mods.botanypots.Crop;
Crop.create("papa_pots_reed_rs1", <item:extrareeds:redstone_reed>, <blockstate:extrareeds:redstone_reed>, 3000, ["sand"]);
Crop.addDrop("papa_pots_reed_rs2", <item:extrareeds:redstone_reed>, 1.0, 1, 1);

Thank you

**Comment by Darkhax** [comment]
CrT doesn't work on 1.16.1 yet. Still working on it but it's taking a bit longer than expected.

**Comment by papaworld** [comment]
Thank you, Darkhax, for your quick turnaround. Looking forward to the updates.

**Comment by Darkhax** [comment]
CraftTweaker support has been re-added but I haven't updated the documentation yet. Here is the WIP docs. https://gist.github.com/Darkhax/0a2e1d3cd9383833335c51e64b705405
