### ISSUE TITLE
Trees option until Bonsai Trees updated?

### ISSUE THREAD

**Issue by tonyvans** [Darkhax-Minecraft/BotanyPots#64]
Hello, This is a great mod. I wanted to ask if there was a way to enable growing of trees? I understand you don't want to step on any toes but Bonsai Trees does not have a 1.16.1 version. (that I could find)
I am playing Enigmatica 6 and was hoping thought a config edit or something I could add it until such time as Bonsai Trees is updated.
Regardless of your response.  great work on a great mod.
Thanks

**Comment by Darkhax** [comment]
Hello. There is no config option to turn this on however you can add trees using [Data Packs](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Datapack-Information) or [CraftTweaker](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/CraftTweaker-Support). It will take a bit of effort to do that but it's currently the only way. I've considered making an addon that would do this but I would want to ask the Bonsai Tree dev if he is okay with that before I actually make it.

**Comment by tonyvans** [comment]
I figured but was hopeful, makes sense, thanks for getting back to me.

**Comment by Yupoman** [comment]
I tried adding them but couldn't get it to work. Maybe it's outdated, I don't know but just in case I copied another data pack to avoid errors, I changed everything to make it like a tree but it doesn't work

**Comment by Yupoman** [comment]
I think it should be the default option, not only because bonsay tree is abandoned, but also to be able to add other mods.

**Comment by Darkhax** [comment]
@Yupoman Bonsai Trees is not abandoned, the author just has real life stuff going on. This year has been quite a lot to deal with for many people. 

I've since spoken with the Bonsai Trees dev and got his permission to release [Botany Trees](https://www.curseforge.com/minecraft/mc-mods/botany-trees) which adds tree support.

**Comment by Yupoman** [comment]
I don't question the free time of each one, but he updated 1.15 in February and from 1.16 he did not even respond to messages.
Beyond that, I understand that they don't copy the trees, but I did not understand why they could not put saplings as in normal pots.

I'm going to try it, although I'm playing 1.16.1, if it works I'll comment. Thanks.
