### ISSUE TITLE
Weird box around crops

### ISSUE THREAD

**Issue by Shindur** [Darkhax-Minecraft/BotanyPots#65]
Using Enigmatica 6 0.2.5 and Botany Pots 1.16.1-3.0.4 there is a weird rendering box around crops. Tested it with and without optifine, the picture attached is without optifine as it still shows up.
![weirdness](https://user-images.githubusercontent.com/20944228/89608359-f2225980-d842-11ea-9b1e-7feb8931f7af.png)

**Comment by Shindur** [comment]
Seems to only affect modded items. Vanilla items render just fine.

**Comment by Darkhax** [comment]
This is now fixed, thanks for reporting.
