### ISSUE TITLE
Support for Saplings

### ISSUE THREAD

**Issue by 4very** [Darkhax-Minecraft/BotanyPots#66]
The ability to put in saplings where you can duplicate the saplings. Either, it will also output wood as well as saplings or just saplings. If you let me know which you would like I can just submit a PR.

**Comment by Darkhax** [comment]
Saplings were intentionally left out because I didn't want to step on the bonsai tree dev's toes. I may reach out to them about this in the future but for now I do not plan to officially support trees.
