### ISSUE TITLE
Botania makes it crash

### ISSUE THREAD

**Issue by Debje** [Darkhax-Minecraft/BotanyPots#72]
I tried to put the vivid grass from the botania mod into the pot and it makes the game crash!
Never mind, it crashes with any type of soil....

**Comment by Darkhax** [comment]
Please include the versions and crash logs.

**Comment by AmazingTriangle** [comment]
I get this crash when I click dirt on to any Botany Pot 1.16.1 version 3.0.6.  I haven't tried it with any other kind of soil. I was using the Valhelsia 3 Modpack and added Botany Pots (https://www.curseforge.com/minecraft/modpacks/valhelsia-3) This is the crash report I got when it crashed.
[crash-2020-08-23_22.42.11-client.txt](https://github.com/Darkhax-Minecraft/BotanyPots/files/5115543/crash-2020-08-23_22.42.11-client.txt)

**Comment by Darkhax** [comment]
Your issue report says you're using a wrong / outdated version of Bookshelf. The current recommended version of Bookshelf for 1.16.1 is 3.6.20.
