### ISSUE TITLE
Add the ability to disable harvest particles

### ISSUE THREAD

**Issue by recon88** [Darkhax-Minecraft/BotanyPots#75]
I have a massive Botany Pots farm and would like to be able to disable the harvest particles as it is decreasing my FPS the more I add.
Yes, you can turn off all particles in Minecraft but that's not a proper solution.

**Comment by Darkhax** [comment]
There is already a config option for this called `breakEffects`.

**Comment by recon88** [comment]
Oh, that's not available for me in the 1.15.2 modpack I'm playing.
Guess I'll have to deal without it.
