### ISSUE TITLE
Support for Variant16x flowers

### ISSUE THREAD

**Issue by Yupoman** [Darkhax-Minecraft/BotanyPots#76]
[variant16x.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5228421/variant16x.zip)

**Comment by Yupoman** [comment]
In case someone wants to try it, that folder goes into the "data" folder

**Comment by Darkhax** [comment]
Thanks for the addition, I will look into adding it soon.

**Comment by Darkhax** [comment]
This is now in the new 1.16.2 version.
