### ISSUE TITLE
Unable to set the Age of a crop via Crafttweaker

### ISSUE THREAD

**Issue by darkphan** [Darkhax-Minecraft/BotanyPots#8]
Would it be possible to add in the ability to set the age property of a crop via crafttweaker?

**Comment by Darkhax** [comment]
You want to set the age block state property on the block that is rendered? CraftTweaker allows you to set properties on blockstates like this `<blockstate:minecraft:grass_block:snowy=true>`.

**Comment by darkphan** [comment]
Ah, thanks!
