### ISSUE TITLE
Adding Crop Via Data Pack

### ISSUE THREAD

**Issue by geohan98** [Darkhax-Minecraft/BotanyPots#81]
Hi

I have been trying to add a crop which is added via mystical customization, I think i have done everything correctly and the datapack gets loaded, this is on the current version of ATM 6 which i have added botany pots too.

[testPack.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5321398/testPack.zip)

**Comment by Darkhax** [comment]
The namespace/modid can not have upper case letters in it.
