### ISSUE TITLE
Can't plant flax on the pots.

### ISSUE THREAD

**Issue by sidyamamoto** [Darkhax-Minecraft/BotanyPots#82]
I think this is related to the inability to get a farmland in the pot because silents gear flax can't be planted on normal dirt or grass.

**Comment by sidyamamoto** [comment]
Forgot to mention the version. 1.16.1.

**Comment by Darkhax** [comment]
Support for each plant needs to be added to the botany pot. AFAIK Silent Gear Flax hasn't been added yet.

**Comment by Darkhax** [comment]
This is now supported.
