### ISSUE TITLE
Water soil

### ISSUE THREAD

**Issue by Yupoman** [Darkhax-Minecraft/BotanyPots#90]
Try making a "water soil" for planting kelp, seagrass, etc. and it works, but you can't see the water block inside the pot.
I tried with "minecraft:water" and different levels in the properties but none worked.

I don't know if I'm doing something wrong or it just can't be done. (As an alternative use a cauldron with level 3 but of course it is not the same)

**Comment by Darkhax** [comment]
Water is not supported because fluids can not be rendered in the pot. Fluid support is a planned feature.

**Comment by Yupoman** [comment]
I understand, it's good to hear.

In case someone else wants to add their aquatic plants, I recommend the lapis lazuli block for the display, it is quite similar to water.

**Comment by Yupoman** [comment]
![Sin título](https://user-images.githubusercontent.com/70600879/95667812-a4c3b080-0b41-11eb-8faf-e0441be98584.png)

**Comment by Darkhax** [comment]
Water soil was added in https://github.com/Darkhax-Minecraft/BotanyPots/commit/a194d41785326f8ec5615967c4047ffd0a7bd96e

Vanilla water crops were added in https://github.com/Darkhax-Minecraft/BotanyPots/commit/899d1a535ffd2f7dfaab57b092b1507b0316e336
