### ISSUE TITLE
Support for some mods and personal changes

### ISSUE THREAD

**Issue by Yupoman** [Darkhax-Minecraft/BotanyPots#91]
First of all I apologize if it is not the place or if it is good to publish it but hey here it is.

I know an update has just been released that adds a lot of these things but hey, these last two days I was doing this because they weren't there yet. It can also be useful for someone who still plays 1.16.1 (like me and my cousins on our server).

And for that same reason keep in mind that some things are wrong or do not make much sense since it was only for personal and decorative use (I mean that the growth values or the things that they give when harvesting them may not be very good).
For example: for tall seagrass a scute is needed, since there is no tall seagrass block. Or the grape plant from the simplefarming mod that needs side blocks to make sense. I also add it although it is horrible.

![Sin título](https://user-images.githubusercontent.com/70600879/95802968-40d1f100-0cd5-11eb-982d-6d58ca82d60f.png)

-Neapolitan support
-Quark: add leaves, sapling, root, turf.
-Sakura Rosea: sapling, leaves.
-Simplefarming: add leaves, sapling, berry bushes, opuntia, fruit log and stick (to put a block of leaves as if it were a small tree), grape plant.
-Autumnity support.
-Builders Crafts & Additions support.
-Decorative Blocks soil (rocky dirt).
-Add the missing _ to the names of the buzzier_bees mod to make it work (only to the folder and the 2 flowers that are available).
-Vanilla: add sapling, leaves, grass, tall grass, vines, large fern (fern can give it), dead bush, cocoa, taller bamboo and sugar cane, sea pickle (waterlogged and not waterlogged), lily pad, kelp, seagrass, tall seagrass, nether sprouts, shroomlight, all corals. Of course, for this I added the water soil, which in this outdated version, since I could not put the water block, I put the lapis lazuli block that looks quite good.
I also took out the nylium blocks from the dirt category and I think something changed with the mushrooms, I don't remember, it is a ton but hey just notice the change.
-Yeah, I stole the saplings from the botany tree and it worked.

I think that's all

Edit: I added the chicory plant, marshmallow and wild plant (simplefarming)
[more.data.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5441314/more.data.zip)

**Comment by Yupoman** [comment]
I missed this plant that I had not seen (simplefarming)
[chicory_root.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5374714/chicory_root.zip)

**Comment by Darkhax** [comment]
Thanks for trying to contribute to this mod. Submitting the files in this way makes it very difficult to review and I haven't had the time to do so properly. It looks like some of these changes have already been done though so I will look through this and see what can be put into the main mod. Some of these changes like trees and dead coral are also better in 3rd party addons because they don't make sense in the main mod.
