### ISSUE TITLE
Mystical Agriculture Certus Quartz

### ISSUE THREAD

**Issue by JDoeBoy** [Darkhax-Minecraft/BotanyPots#97]
I have tried adding a .json file manually, using an edited copy of the wheat recipe, only changing the input seed, and output item.

`{
    "type": "botanypots:crop",
    "seed": {
      "item": "mysticalagriculture:certus_quartz_seeds"
    },
    "categories":["dirt"],
    "growthTicks": 3,
    "growthModifier": 1.2,
    "display": {
      "block": "mysticalagriculture:certus_quartz_essence",
      "properties": {
        "age": 7
      }`
That is what I have in the top of the file that I named certus_quartz.json, and I have tried various names for the .json file.

Is this me?

I added the following

`    "conditions": [
      {
        "type": "forge:mod_loaded",
        "modid": "mysticalagriculture"
      }`

and it still is not working

**Comment by andrewsf** [comment]
You are missing two closing curly brackets in your first code sample and a closing square bracket in your second code sample.

I would suggest starting with one of the existing Mystical Agriculture recipes, such as [nether_quartz.json](https://github.com/Darkhax-Minecraft/BotanyPots/blob/1.16.3/src/main/resources/data/mysticalagriculture/recipes/crops/nether_quartz.json). 

Consider just using [the one that @Warbringer12 already made](https://github.com/Darkhax-Minecraft/BotanyPots/blob/32da60ba71346f4d17060ed4f63feecd091cf6d2/src/main/resources/data/mysticalagriculture/recipes/crops/certus_quartz.json).

**Comment by Darkhax** [comment]
The PR that was mentioned has now been merged.
