### ISSUE TITLE
[1.16.3] Watch of flowing time Permanently breaks all hoppers

### ISSUE THREAD

**Issue by raziel23x** [Darkhax-Minecraft/BotanyPots#98]
Forge 34.1.25
BotanyPots-1.16.3-5.1.9.jar
BotanyTrees-1.16.3-1.0.7.jar
projecte-1.0.4-universal.jar 

with the latest git at this time @ https://github.com/sinkillerj/ProjectE/commit/8b14e00322ab3d9af72ac07e18bf679ac75e3c36 build for 1.16.3 I was playing around with the Botany pots and Botany tree mod and noticed if you use the watch of flowing time in the room near them when trying to speed up the growth of the pots instead of speeding up the time they grow it stops time for growth permanently even after disabling the watch on the pedestal even if you break both items and its permanently even if you break the pots and place them back down.... not sure if it's bug with that mod or not as the only way to fix them is to delete the save and start a new one as it breaks all the pot even future ones placed down so maybe it's something that breaks in that mod instead

**Comment by Darkhax** [comment]
I can not reproduce this issue using https://github.com/sinkillerj/ProjectE/commit/28fc60da734390ca63ab8529608b1897d65389e6. Did your pots just run out of output space?

[watch-test-world.zip](https://github.com/Darkhax-Minecraft/BotanyPots/files/5579171/watch-test-world.zip)
