### ISSUE TITLE
[Feature Request for 1.15.2+] Resynth - Growable Ores & Resources Support

### ISSUE THREAD

**Issue by seanimusprime** [Darkhax-Minecraft/BotanyPots#99]
Resynth compatibility would be great to help with simple resource automation. https://www.curseforge.com/minecraft/mc-mods/resynth

**Comment by Darkhax** [comment]
Hello,

Yes it is possible to add support. It looks like they have ~125 new crops though so this will take some time.

**Comment by ngoetti** [comment]
Does this mod still exist? @seanimusprime This link is down: https://www.curseforge.com/minecraft/mc-mods/resynth/files

**Comment by Darkhax** [comment]
I can't seem to find the mod anymore. I am also focusing on 1.18.2+ for now. Community contributions to 1.16.5 are still welcome.
